### ISSUE TITLE
Is there anything wrong when spliting train/test dataset? 

### ISSUE THREAD

**Issue by loveychen** [Rayhane-mamah/Tacotron-2#100]
In the `tacotron.feeder.Feeder#__init__` method:
```python
#Make sure test_indices is a multiple of batch_size else round up
len_test_indices = self._round_up(len(test_indices), hparams.tacotron_batch_size)
extra_test = test_indices[len_test_indices:]
test_indices = test_indices[:len_test_indices]
train_indices = np.concatenate([train_indices, extra_test])
```
As the comment here states, the number of test dataset should be a multiple of the batch_size.  If not, we should move some examples from the train dataset to the test dataset. But the code here indicates moving  examples from test to train dataset.
And always `len_test_indices >= len(test_indices)`, so `extra_test` is always an empty list, so these codes do not work as expected all the time.

I am just begin reading this repository these days, and have not gone through the whole project. I cannot figure out whether this is a mistake or I misunderstand it.

**Comment by Rayhane-mamah** [comment]
Hello @loveychen!

Haha yes you are right, I meant to set line 47 as:
len_test_indices = self._round_up(len(test_indices), hparams.tacotron_batch_size) - hparams.tacotron_batch_size

thanks for reporting this, I fixed this in latest commit. :)
Closing the issue, if you notice any more bugs with this part, feel free to reopen :)
