### ISSUE TITLE
Whether the first and the end silence clips have some impact on the model ？

### ISSUE THREAD

**Issue by v-yunbin** [Rayhane-mamah/Tacotron-2#103]
Some noises exist in synthetic speech, so i listen to some samples and find some noises exist in 
silence clips of samples.
Due to it, removing the first and the end silence clips of samples maybe beneficial to trained model
Do you think so or different viewpoint ?

**Comment by v-yunbin** [comment]
anyone have some suggestion?

**Comment by cobr123** [comment]
https://github.com/keithito/tacotron/issues/159#issuecomment-400973598

**Comment by v-yunbin** [comment]
@cobr123 3ks
