### ISSUE TITLE
Tacotron synthesis is not recognising the hparams.py sentences

### ISSUE THREAD

**Issue by dsilva-tbox** [Rayhane-mamah/Tacotron-2#107]
When I try to synthesise sentences using Tacotron, the output are random sentences from training data rather than the written sentences in hparams.py. 

How can I redirect the Tacotron to read and say the sentences from hparams.py?

**Comment by hyzhan** [comment]
use --text_list XXX.txt in synthesize.py

**Comment by Rayhane-mamah** [comment]
You may be running synthesis in GTA mode, please refer to the README.md for instructions on eval synthesis:

> python synthesize.py --model='Tacotron' --mode='eval' --GTA=False

This should do the work. closing the issue to reduce their number and keep issues manageable. If the problem persists, feel free to reopen :)
