### ISSUE TITLE
WaveNet Assertion at GTA=True 

### ISSUE THREAD

**Issue by karamarieliu** [Rayhane-mamah/Tacotron-2#111]
When I run the code (same hparams except train_w_gta = True), the WaveNet training crashes due to the following error: Exception in thread background:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kara/wavenet/wavenet_vocoder/feeder.py", line 208, in _enqueue_next_train_group
    feed_dict = dict(zip(self._placeholders, self._prepare_batch(batch)))
  File "/home/kara/wavenet/wavenet_vocoder/feeder.py", line 253, in _prepare_batch
    batch = self._adjust_time_resolution(batch, self.local_condition, max_time_steps)
  File "/home/kara/wavenet/wavenet_vocoder/feeder.py", line 336, in _adjust_time_resolution
    self._assert_ready_for_upsample(x, c)
  File "/home/kara/wavenet/wavenet_vocoder/feeder.py", line 366, in _assert_ready_for_upsample
    assert len(x) % len(c) == 0 and len(x) // len(c) == audio.get_hop_size(self._hparams)

It appears that when GTA is true, for some samples in batches, the length of gta_output/gta/speech_mels... is exactly one less the necessary length such that len(c) + 1 would make the assertion true. 
Is this happening for anyone else / how would I fix it??

Edit: I hacked it by extending the Mel file c by 1 matrix if it is short such that c = np.concatenate((c, [c[-1]]), axis =0) but this obviously isn't a solid solution, just a temp fix so I could get it up working.

**Comment by Luzeru** [comment]
@karamarieliu 
hi ：
I have the same problem. 
Have you solved it?
Can you give me some advice？

**Comment by karamarieliu** [comment]
I haven't solved it but I fudged it so it runs accordingly. What I did was just extend the Mel file by 1 matrix if it's one short, which I figured wouldn't do too much damage as you are just extending the last sound file by one timeframe I believe. My code in https://github.com/karamarieliu/gst-tacotron-wavenet uses style tokens so there will be a different architecture but you can see how I hacked it in feeder.py.

**Comment by Rayhane-mamah** [comment]
Hello there, @karamarieliu well done figuring this out. I have set your solution for now, it indeed won't have much effect unless the random pick picks the end of a speech for training. I just made a small modification compared to your hack where I add a silence padding for the last frame instead of repeating the final frame. Thanks again for this trick.

If your problem persists after latest commit, please feel free to reopen.
