### ISSUE TITLE
Generated wave sample comparison between old version and latest version

### ISSUE THREAD

**Issue by v-yunbin** [Rayhane-mamah/Tacotron-2#112]
1. old version
![image](https://user-images.githubusercontent.com/38179632/43186828-73653122-9022-11e8-9bb5-ab9bb1c1b9a5.png)
[step-20000-waveform-linear.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2227018/step-20000-waveform-linear.zip)

2. new vesion
![image](https://user-images.githubusercontent.com/38179632/43187109-2f744682-9023-11e8-9bf3-21eb3a2c913f.png)
[step-20000-wave-from-mel.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2227020/step-20000-wave-from-mel.zip)

**Comment by IlievskiV** [comment]
What is the new version?

**Comment by begeekmyfriend** [comment]
It is improper to compare between linear and mel outputs.

**Comment by v-yunbin** [comment]
@begeekmyfriend what you said is reasonable.
new  version mel samples on step 33k
![image](https://user-images.githubusercontent.com/38179632/43244454-4753dd52-90dd-11e8-90d3-ca356aecf21c.png)
old  version mel samples on step 33k
![image](https://user-images.githubusercontent.com/38179632/43244489-775d1680-90dd-11e8-9777-4960c2a50f4e.png)
