### ISSUE TITLE
can't synthesize audio like human voice when executing "python synthesize.py --model='WaveNet'"

### ISSUE THREAD

**Issue by NewEricWang** [Rayhane-mamah/Tacotron-2#115]
Hi, all
I used wavenet model to generate audio, but I only got full-noisy audio. The command is as follows:
"python synthesize.py --model='WaveNet'", .
The used model is 360k-step wavenet model trained on LJ-speech database. 
Moreover, I found the predicted waves in eval-dirs/wavs also are noise. I guess the wavenet  model don't coverage at 360k-step.

Any help will be appreciated!

**Comment by butterl** [comment]
150K+  would get good training wav plot for me, but not success in eval

**Comment by karamarieliu** [comment]
My guess is that if you're only using WaveNet to eval, it might not work on its own since this is a modified version of the original WaveNet (see paper for T2)? I could be wrong though.

**Comment by NewEricWang** [comment]
@karamarieliu, Yes, I am only using WaveNet to eval.

**Comment by Starlon87** [comment]
Same issue. 

Use the 110k  steps model of WaveNet.
Run ' python3 synthesize.py --model='WaveNet' '
The wav file in '/wavenet_output/wavs' is full-noisy.

**Comment by Starlon87** [comment]
@Yeongtae

I have try below commit ,but still noisy, should I retrain it and use the new model to try?

https://github.com/Rayhane-mamah/Tacotron-2/pull/110

**Comment by NewEricWang** [comment]
@Starlon87 ， Same issue! I also have try  #110 commit ,but still noisy.

**Comment by Yeongtae** [comment]
@Starlon87, @NewEricWang 
I just fix a bug that don't load trained Wavenet model in synthesize time.

There is a solution about your problem.
https://github.com/Rayhane-mamah/Tacotron-2/files/2145382/models.tar.gz,

Change parameters in hparams.py
image

**Comment by NewEricWang** [comment]
@Yeongtae , thank you for your help! But my wavenet model is trained by using input_type="raw".

**Comment by NewEricWang** [comment]
@Yeongtae, I can load the WaveNet model trained by using this original repo successfully. But the generated audio is noise.  So I wonder whether my issue can't be solved by your provided solution.

**Comment by Yeongtae** [comment]
@NewEricWang 'raw' is hard to train. Your model don't converge maybe.  
Though I use 'mulaw', my model don't converge. I'm trying to figure out the problem.

**Comment by ilhamprayudha** [comment]
@Yeongtae  I've tried using the above solution, but the noise generated noise, whether because it uses 8-bit & mulaw ?

**Comment by Rayhane-mamah** [comment]
Hello friends,

This issue is yet another duplicate of https://github.com/Rayhane-mamah/Tacotron-2/issues/57

I am just going to leave few more notes and close the issue.

- This has been fixed in latent commit.
- If using "raw' mode,  you may want to train for 1 million steps (according to parallel wavenet paper)
- Also it's a good idea to train your model using GTA spectrograms from tacotron (can be set in **hparams.py**)
- If the problem persists, feel free to reopen!

**Comment by ilhamprayudha** [comment]
How about "We also present timings for
sample generation, demonstrating more than 1000× speed-up relative to original WaveNet." In paper paralel wavenet.

I generate take along time

**Comment by ilhamprayudha** [comment]
![image](https://user-images.githubusercontent.com/26913017/43749230-676603c4-9a1d-11e8-9fdd-c9a7844860e4.png)
so in this image pre-trained teacher wavenet not as practice after student wavenet ?

**Comment by Rayhane-mamah** [comment]
The pre trained teacher is used as output distribution conditionner for the student. The student is considered trained when both output distributions are about the same.
