### ISSUE TITLE
Eva data of WaveNet is really bad, and the average error always keep around 7 for 140k steps

### ISSUE THREAD

**Issue by FeiCoding** [Rayhane-mamah/Tacotron-2#120]
![step-140000-waveplot](https://user-images.githubusercontent.com/25921921/43675090-26d91e66-97d6-11e8-88df-cf64bab887a6.png)
![2018-08-04-110614_2909x1143_scrot](https://user-images.githubusercontent.com/25921921/43675105-76947e5a-97d6-11e8-84ea-d5c75d8b0e8c.png)

Is this normal?

or maybe some bugs in Wavenet?

dose anyone get the similar problems?

I use GTX 1080 to train, 

the wavenet_batch_size = 2

**Comment by Rayhane-mamah** [comment]
Hello @FeiCoding thanks for reaching out.

I fixed this in last commit, it is merely a synthesis time bug. Also please keep in mind that for "raw" mode, you need to train your model for about 1 million steps to get human like speech. (yeah it takes time to converge..)

This is a similar issue to yours:
https://github.com/Rayhane-mamah/Tacotron-2/issues/57

So I am closing this now, if your problem still persists with latest commit, feel free to reopen.
