### ISSUE TITLE
Synthetic audio exists some wrong pause for chinese

### ISSUE THREAD

**Issue by v-yunbin** [Rayhane-mamah/Tacotron-2#122]
#######English#####
Synthetic audio exists some wrong pause for Chinese.
It sonds Unfluency and even change the original meaning of the sentence
true: yu2 jian4 jun1 wei4 mei3 ge4 you3 cai2 neng2 de5 ren2 ti2 gong1 ping2 tai2 / ta1 shi4 yin1 pin2 ling3 yu4 de5 tao2 bao3 tian1 mao1.
Synthetic audio: yu2 jian4 jun1 wei4 mei3 ge4 you3 cai2 neng2 de5 ren2 ti2 gong1 ping2/tai2 ta1 shi4 yin1 pin2 ling3 yu4 de5 tao2 bao3 tian1/ mao1.
wave sample:
[speech-wav-00001-linear.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2261093/speech-wav-00001-linear.zip)
Anyone for Chinese has same problem?
######Chinese#######
合成的语音里面的停顿明显是错误的，请问大家有遇到同样的问题的么？
实际断句：他是音频领域的淘宝天猫，在这个平台上
合成断句：他是音频领域的淘宝天，猫在这个平台上

**Comment by begeekmyfriend** [comment]
Please check if there is punctuation in your training dataset.

**Comment by begeekmyfriend** [comment]
Yes, but I would prefer
> lv4 , shi4 yang2 chun1 yan1 jing3 , da4 kuai4 wen2 zhang1 de5 di3 se4 .

**Comment by v-yunbin** [comment]
thanks, see.

**Comment by v-yunbin** [comment]
@begeekmyfriend when to synthetic speech with pinyin, also must has punctuation in pinyin?
