### ISSUE TITLE
There are some indent errors in latest commit

### ISSUE THREAD

**Issue by Yeongtae** [Rayhane-mamah/Tacotron-2#128]
I'm trying to run " python train.py --model='WaveNet' " with latest commit.

When I test it, I can see an indent error in "/tacotron/train.py"
![image](https://user-images.githubusercontent.com/13597229/43783003-9c9e7f7a-9a9b-11e8-9cc3-c1c5605dd1e8.png)

**Comment by hiroto911** [comment]
@Yeongtae 
#129 Fix here!

**Comment by Rayhane-mamah** [comment]
Thanks @hiroto911 for the quick fix.

**Comment by Yeongtae** [comment]
Thanks @hiroto911

**Comment by Yeongtae** [comment]
When I test the latest commit, 
I can see an error...
![image](https://user-images.githubusercontent.com/13597229/43786721-4bba43b0-9aa4-11e8-9be0-fb618fa01450.png)

**Comment by Rayhane-mamah** [comment]
@Yeongtae there seems to be few bugs here and there, give me a second I'll debug the whole thing and push a new commit for both your issues. Sorry for the inconvenience.

**Comment by hiroto911** [comment]
@Rayhane-mamah @Yeongtae 
tacotron/train.py L162 There was still a misalignment of indentation...

It is my mistake because I got a fixed commit in a hurry. Sorry...

**Comment by Rayhane-mamah** [comment]
Things should go smooth with (e2c22755daabcddf9fb0bf70f72d7c878fc876a2)  @Yeongtae, let me know if you find any others problems :) (I made few tests so it should be fine).

**Comment by Rayhane-mamah** [comment]
I believe these were solved so we're closing the issue. Feel free to reopen if you notice any further problems related to this issue :)
