### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by metaln37** [Rayhane-mamah/Tacotron-2#13]
Hello,

I'm trying to train your model with my custom Russian language data on GeForce GTX 1080 with 8Gb RAM. And when batch_size is set to anything greater than 8, I'm constanly getting out of memory error somewhere between steps 8-19. Do you have any idea why could it happen? 
```
2018-04-10 16:52:27.494495: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 591.41MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-04-10 16:52:37.495788: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 118.28MiB.  Current allocation summary follows.
2018-04-10 16:52:37.540543: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ****************************************************************************************************
2018-04-10 16:52:37.540674: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at random_op.cc:202 : Resource exhausted: OOM when allocating tensor with shape[16,3785,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Exiting due to exception: OOM when allocating tensor with shape[16,3785,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/dropout_conv_layer_2_postnet_convolutions/dropout/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model/optimizer/gradients/model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/dropout_conv_layer_2_postnet_convolutions/dropout/div_grad/Shape)]]

Current usage from device: /job:localhost/replica:0/task:0/device:GPU:0, allocator: GPU_0_bfc
  154.23MiB from model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/dropout_conv_layer_2_postnet_convolutions/dropout/div
  118.28MiB from model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/conv1d/conv1d/Conv2D
  118.28MiB from model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/batch_normalization/batchnorm/mul_1
  118.28MiB from model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/dropout_conv_layer_1_postnet_convolutions/dropout/div
  118.28MiB from model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/dropout_conv_layer_1_postnet_convolutions/dropout/random_uniform/RandomUniform
  118.28MiB from model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/conv1d/conv1d/Conv2D
  118.28MiB from model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/batch_normalization/batchnorm/mul_1
  32.00MiB from model/optimizer/gradients/model/loss/L2Loss_16_grad/mul
  28.00MiB from model/optimizer/gradients/model/loss/L2Loss_15_grad/mul
  19.99MiB from model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/conv1d/conv1d/Conv2D
  18.48MiB from model/inference/decoder/transpose
  18.48MiB from model/optimizer/gradients/model/loss/mean_squared_error/Sum_grad/Tile
  17.06MiB from model/inference/embedding_lookup
  17.06MiB from model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/batch_normalization/batchnorm/mul_1
  17.06MiB from model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/dropout_conv_layer_1_encoder_convolutions/dropout/div
  17.06MiB from model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/dropout_conv_layer_1_encoder_convolutions/dropout/random_uniform/RandomUniform
  17.06MiB from model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/conv1d/conv1d/Conv2D
  17.06MiB from model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/batch_normalization/batchnorm/mul_1
  17.06MiB from model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/dropout_conv_layer_2_encoder_convolutions/dropout/div
  17.06MiB from model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/dropout_conv_layer_2_encoder_convolutions/dropout/random_uniform/RandomUniform
  17.06MiB from model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/conv1d/conv1d/Conv2D
  17.06MiB from model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/batch_normalization/batchnorm/mul_1
  17.06MiB from model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/dropout_conv_layer_3_encoder_convolutions/dropout/random_uniform/RandomUniform
  17.06MiB from model/inference/encoder_LSTM/concat
  17.06MiB from model/optimizer/gradients/model/inference/decoder/while/CustomDecoderStep/MatMul/Enter_grad/zeros
  16.06MiB from model/inference/encoder_LSTM/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
  16.06MiB from model/inference/encoder_LSTM/bidirectional_rnn/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
  8.34MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  7.32MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  5.36MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_1_grad/mul
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_4_grad/mul
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_7_grad/mul
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_26_grad/mul
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_29_grad/mul
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_32_grad/mul
  5.00MiB from model/optimizer/gradients/model/loss/L2Loss_35_grad/mul
  4.27MiB from model/optimizer/gradients/model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add/Enter_grad/zeros
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  4.27MiB from model/inference/decoder/while/CustomDecoderStep/Location_Sensitive_Attention/add
  Remaining 41046 nodes with 5.32GiB
```

**Comment by Rayhane-mamah** [comment]
Hello @metaln37, thanks for reaching out!

Memory errors are due to 3 major factors:

- length of your dataset: depending on the language and on your data, your RAM (or VRAM) can be exhausted, especially if the data has too many mel frames to predict. (For my case in Ljspeech for example, the longuest sentence has 870 mel frame, so at worst, the model makes 870 decoding step.). Please note that each decoding step consumes memory.
- Batch size: depending on your data samples length, you adapt your batch size to be the biggest possible without memory errors. 
- Reduction factor (outputs_per_step): by decreasing this parameter (to 1) the model consumes up to 2x more VRAM than with a reduction factor of 5 as this reduces the number of decoding steps as well.

So for your case. Your GPU load is saturating really fast, I would first want to check howa you do your preprocessing, maybe tweak a little bit with it, note that sample rate and fft size will affect the num of mel frames in your data, so try reducing the number of mel frames without influencing the audio quality!

You can use the notebook in this repo to invert real preprocessed data and try to judge if quality is good enough.

If hparams are all good, then you data is simply too long, or your feeder isn't optimal. I would recommend making batches with same lenght to minimize the padding and thus size of data (like in our **feeder.py**).

If that is good too, then your data samples are simply too long.

I wouldn't recommend to pick a reduction factor higher than 5 because it will add noise in the outputs of the model.

I will however try finding some ways to reduce memory usage even more. 

Meanwhile, if you notice any difference between my work and the code you're running, please notify me!

**Comment by imdatsolak** [comment]
One thing we have seen is that the audio-files should never be larger than 20 seconds, on average they should be around 12-14 seconds. We are using GeForce GTX 1080 Ti with 11GB. At batch-size 32, the GPU is using around 8GiB using the default settings in hparams.

Another important factor is the sample-freq. We are using 16KHz; anything above that requires batch-size to be reduced to 24, 16, 8 or even further - even with our 11GiB VRAM.

**Comment by metaln37** [comment]
Looks like removing all wavs longer than 20s from dataset solved a problem. Now it works with batch_size=16.

Currently we working on proprietary version of tacotron-2 based on keithito work, and I want to share some results. Our dataset consists of about 23 hours of audio, and about half of utterances consist of one or two words. Here are samples for comparison:
[https://metaln37.github.io/Tacotron2-samples/](https://metaln37.github.io/Tacotron2-samples/)

Hyperparameters we changed in your model: **fft_size = 400, hop_size = 100, sample_rate = 8000, fmin = 0, fmax = 4000, outputs_per_step = 7, tacotron_batch_size = 16** 

We also trained our model on LJspeech dataset (sample is on the link above). Main difference of our version of tacotron - generation of one frame per step. This was achieved by customizing training helper and feeding each 10th frame from ground truth (other 9 are decoder outputs).
Also we don't use stop token yet, since our model unable to learn alignments with it. Instead we use kind of hack: **finished = tf.less(tf.reduce_sum(outputs), 0)**, but it works pretty well.

**Comment by Rayhane-mamah** [comment]
So your model is something like a tacotron based on keithito's hybrid work with a teacher forcing ratio equivalent to 0.1

Yeah working with bigger batch size is hard in those conditions. I also tried keithito's work once out of curiosity and I noticed it consumes more memory than our repo (probably to the size of his decoder and post processing net).

Also, generating one frame at a time surely helps overall quality but also consumes more memory.

If I were in your position, I would definitely start by trying to reduce the model size. For example the stateful attention RNN in tacotron 1 is proven to be no longer needed in T2. 

Are your models capturing attention with this batch size? I experienced a difficulty in getting the right alignments with a batch size of 8.

**Comment by imdatsolak** [comment]
@Rayhane-mamah: the reason why the M-AILABS Speech Dataset contains only wav files with average 15 seconds is based on the experience I explained above. The longer the wav files, the more difficult it becomes (that was our experience) to learn (including OOM-problems).

We tried larger wav files (20-50 seconds) with T, T2, WaveNet, WaveNet2 and many other engines out there. The max=20 sec was the best estimate we came up with. This works better also for Speech Recognition (STT). We have developed an in-house STT-engine based on Baidu's DeepSpeech and even Baidu recommends wav-files to be no longer than 20secs.

Just FYI

**Comment by Rayhane-mamah** [comment]
Hello again @metaln37  and @imdatsolak.

I confirm @imdatsolak that wavs longer than 20 sec might be extremely challenging, not only for the hardware, but also for the model to actually learn. (especially alignment becomes harder I'm guessing).

@metaln37, So finally my main GPU is now free to work on T2 project, so here is a picture I took a while ago that contains enough information on the model's Memory usage.
![screenshot from 2018-04-12 23-01-07](https://user-images.githubusercontent.com/34689728/38707408-29194c36-3ea9-11e8-96ae-8c6a075ebb31.png)

Please note that in this picture, I am training the model with a batch size of 64 but with a reduction factor of 5 (Consumes 8Gb or VRAM). 

I am also thinking about experiencing with Tensorflow XLA JIT support to see if it can help even more. I'll keep you informed.

**Comment by StevenZYj** [comment]
Hi @Rayhane-mamah .

I'm facing the same problem. It seems like training with reduction_factor=1 is too much for a 11GB GPU, since I've already reduced the sampling rate to 18KHZ for my own dataset (maximum mel frame length is around 1300). I wonder if you have tried r=1 and any recommendations on hyperparameter setting?

The reason I want to try r=1 is that I think it is better for wavenet training, right?

**Comment by begeekmyfriend** [comment]
In my opinion, `r==2` is nearly equal to `r==1`.

**Comment by StevenZYj** [comment]
That's good to know. I think I might need to reduce my batch size. Currently it is set to 32.

**Comment by Jeff-Winchell** [comment]
@Rayhane-mamah wrote
> I wouldn't recommend to pick a reduction factor higher than 5 because it will add noise in the outputs of the model.

I used 20 because I only have 4 GB GPU memory and thought that keeping batch size=32 was better than batch size=16 with a reduction factor of 4. At least it was for performance. Maybe the evaluation samples sound worse because of this? I can't compare to the batch size 16 because rerunning the code blew away my logs (BTW, consider a more elaborate directory structure because the current one destroys everything you did with previous training on different parameters).

I hope to soon have a much faster GPU with 16 GB memory so I can test out this reduction factor (speed vs noise) question.
