### ISSUE TITLE
There is no load_averaged_model method in tacotron/train.py file

### ISSUE THREAD

**Issue by wushicanASL** [Rayhane-mamah/Tacotron-2#130]

**Comment by Rayhane-mamah** [comment]
Hello @wushicanASL, where is the bug in that? There isn't supposed to be a moving average on tacotron side, we only use the [EMA](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage) on wavenet.

If you didn't make any change in our code, please specify the steps to reproduce your bug?

**Comment by hiroto911** [comment]
#133 Fix it!!!

**Comment by Rayhane-mamah** [comment]
Hahaha my bad I didn't notice that one, @Hiroto911 at the rescue once again.
