### ISSUE TITLE
Trimming in wavenet_vocoder/feeder.py

### ISSUE THREAD

**Issue by atliSig** [Rayhane-mamah/Tacotron-2#135]
Hey, I just noticed a likely bug in line 376 in `wavenet_vocoder.feeder._adjust_time_resolution` where it says `x=audio.trim(x)` rather than `x=audio.trim_silence(x, self._hparams)`.

**Comment by Rayhane-mamah** [comment]
Hello @atliSig, you are perfectly right! I am sorry I let that slip, I never used Wavenet without local conditioning.. Actually congrats, you might be the first one to do so! :)

Anyway, I will fix this for next programmed commit (tomorrow). Thanks for your contribution

**Comment by Rayhane-mamah** [comment]
We fixed that, thanks for your contribution!
