### ISSUE TITLE
Multi-language Support?

### ISSUE THREAD

**Issue by jinfagang** [Rayhane-mamah/Tacotron-2#15]
Is there any multi language support planning, such as Chinese? Or any instructions for prepare dataset for training?

**Comment by jinfagang** [comment]
I will work on that after I finish my graduate paper :). I wanna build an robot which can making voice.

**Comment by Rayhane-mamah** [comment]
That's an awesome project, good luck!

I would love to see how it goes.

**Comment by Rayhane-mamah** [comment]
UPDATE:
You can refer to [this issue](https://github.com/Rayhane-mamah/Tacotron-2/issues/18) for an example of my repo's adaptation to work with Chinese Mandarin.

@begeekmyfriend 's [mandarin branch](https://github.com/begeekmyfriend/Tacotron-2/tree/mandarin) can be found here.

**Comment by jinfagang** [comment]
Thanks Ray. Will check it out.
