### ISSUE TITLE
librosa.output.write_wav no longer works with non-float types

### ISSUE THREAD

**Issue by dsmiller** [Rayhane-mamah/Tacotron-2#16]
As described [here](https://github.com/librosa/librosa/issues/640), this change breaks [audio.py](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/datasets/audio.py#L14) and librosa seems to want to keep it that way.

An alternative is 
`scipy.io.wavfile.write(path, hparams.sample_rate, wav.astype(np.int16))`

**Comment by Rayhane-mamah** [comment]
Hello @dsmiller.

I noticed that too a while ago, but I didn't pay much attention considering that I'm using the same librosa version as in **requirements.py** (which still supports integer type audio).

Anyways, I'm glad you proposed this permanent solution. Thank you very much for you contribution!

You solution has been adopted in the latest commit (0330bd0161e4530acbb7bc2db00a1db95b2dc107)
