### ISSUE TITLE
Does preemphasis matter in audio signal processing?

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#160]
I saw there is [preemphasis](https://github.com/keithito/tacotron/blob/master/util/audio.py#L28) before STFT in T1 and being removed in T2, is it necessary?

**Comment by Rayhane-mamah** [comment]
euuhm I don't know really, I used to use it before but I didn't really see any major differences. I think I took it off afterwards because it was distorting the target distribution shape or something.

**Comment by begeekmyfriend** [comment]
Thanks for you explanation.
