### ISSUE TITLE
Noisey Wavenet Synthesis

### ISSUE THREAD

**Issue by avivelor** [Rayhane-mamah/Tacotron-2#166]
Hi all,

I've currently ran my model for 120,000 tacotron steps and 140,000 wavenet steps with Tacotron-2 and decided to try out the synthesis command. After synthesis on the default setting, all the audio for my wavenet output was static and gibberish, is this normal at the step amounts that I'm at (I noticed the default wavenet steps are 1,300,000)?

Thanks!
![wavenet-waveplot-mel-17](https://user-images.githubusercontent.com/17033978/44441999-714df280-a584-11e8-90b9-30c019788d85.png)
![mel-17](https://user-images.githubusercontent.com/17033978/44442007-7b6ff100-a584-11e8-86c4-acacb9f6a8bb.png)
![alignment-17](https://user-images.githubusercontent.com/17033978/44442010-7d39b480-a584-11e8-99f1-8f5e485cd7f6.png)

**Comment by Rayhane-mamah** [comment]
Hello @avivelor, yes it usually takes a lot more steps to make good quality. I am experimenting with ways to make it converge faster, I'll keep you posted ;)

**Comment by avivelor** [comment]
Thanks for the speedy reply @Rayhane-mamah!
