### ISSUE TITLE
The problem of the minimum lr of wavenet.

### ISSUE THREAD

**Issue by Yeongtae** [Rayhane-mamah/Tacotron-2#183]
In my opinion, It hinders convergence.

#156 
My model state is below. 
1260K iteration
![image](https://user-images.githubusercontent.com/13597229/45008832-bc194100-b03f-11e8-815d-c2dd9a6c273c.png)

Synthesis samples.
[synthesis.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2347084/synthesis.zip)

A few days later, I will update my results with minimum lr 1e-8

**Comment by tdplaza** [comment]
could you post some plot images of begining steps, say ~1000 - 5000. 
![step-1200-waveplot](https://user-images.githubusercontent.com/31118781/45014143-79b02e00-b058-11e8-83d2-fcb31e5d3e7e.png)
![step-1400-waveplot](https://user-images.githubusercontent.com/31118781/45014144-79b02e00-b058-11e8-890f-e924f385921a.png)

Because i have just tried to train Wavenet with 5000 steps, I have no idea that I'm going right or wrong way. Could you please show me how good your Wavenet model is in first 5000 time steps?

**Comment by lkfo415579** [comment]
@Yeongtae  I tried this 8 bit method but it converges too fast, even in the first batch it got **avg_loss=0.00019**, before it can save the first model the program already pops up error of gradient exploded.

**Comment by Yeongtae** [comment]
@lkfo415579 Feel free. You need more time.

See my experiments.
I figured out that minimum lr 1e-4 makes it hard to converge.


It is my first experiment.
![image](https://user-images.githubusercontent.com/13597229/45135502-b4da6a80-b1da-11e8-86d7-7bc93de5c00f.png)
[ex1.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2355484/ex1.zip)
Though most of the voice sounds natural, it has failed to converge. 
Because it synthesize wavs with noise.

It is my second experiment. 
![image](https://user-images.githubusercontent.com/13597229/45135451-6b8a1b00-b1da-11e8-8afa-06f92e300da5.png)
[ex2.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2355479/ex2.zip)
Though second ones had less iteration, It's done to converge, maybe.
Because it makes clear wavs.

My conclusion is that Learning with less lr helps to converge.

**Comment by tdplaza** [comment]
Can you help me? 
My model traning results good sound, but the sound is not good in eval folder. (in 30,000 training steps)

Does this normal? Does your model act like that? (I wanted to checkout synthesize results, but it still has problem so I could not run synthesis)

Here is my training and evals results. As you can hear, the traning results is so good, but evals. :(.

Thank for your helps.  

[eval-dir.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2359228/eval-dir.zip)
[training_dir.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2359229/training_dir.zip)

**Comment by tdplaza** [comment]
oh, thank you so much. I understood

**Comment by sid-sundrani** [comment]
Off topic, but why is the Wavenet loss becoming more negative, as opposed to its magnitude tending to 0?
