### ISSUE TITLE
file problem

### ISSUE THREAD

**Issue by Suryansh5545** [Rayhane-mamah/Tacotron-2#187]
I installed tensorflow with anaconda but don't know where i have to place tacotron 2 master folder also the command for installing requirement is showing "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' " error and i am a complete new to this please help me

**Comment by peter05010402** [comment]
you can use "pip3 install -r requirements.txt"

**Comment by Suryansh5545** [comment]
i tried but same and also where to put that pacotron 2 master file?
