### ISSUE TITLE
Can't synthesize, Key model_1/model/inference/decoder/Location_Sensitive_Attention/attention_bias/ExponentialMovingAverage not found in checkpoint

### ISSUE THREAD

**Issue by hadaev8** [Rayhane-mamah/Tacotron-2#190]
I trained the model for a month
Used code from e2f9780 commite
But now I can't synthesize
I fixed variables names in checkpoint 
But now no idea what to do with this error
Key model_1/model/inference/decoder/Location_Sensitive_Attention/attention_bias/ExponentialMovingAverage not found in checkpoint
As far as I see, there is no such variable in checkpoint

Any way to fix it?
Pls halp

**Comment by tdplaza** [comment]
there is another same question. Check #163

**Comment by hadaev8** [comment]
Yes, I saw a lot of reports about it, but nothing helpful.
I see your answer about optimizer, but shouldn't here be same optimizer?

**Comment by tdplaza** [comment]
Since synthesizing does not require optimizer. So if you are trying to synthesize, that maybe other problem.

**Comment by hadaev8** [comment]
I bypassed this bug by using tacotron and then wavenet synthesize separately, maybe it helps someone.
