### ISSUE TITLE
How to control  Speed ​​of speech in wav file

### ISSUE THREAD

**Issue by peter05010402** [Rayhane-mamah/Tacotron-2#195]
Hello,all!
After train the tacotron,if synthesize by eval modes, How could I control the speed of speech in wav file?

**Comment by tdplaza** [comment]
the save_wav function has a parameter call sr (or sample_rate) this rate is your wav speed.

by default, sample_rate is loaded from hparams. you can change this param to control the wav rate.

**Comment by peter05010402** [comment]
@tdplaza Thank you! I got it!
