### ISSUE TITLE
WaveNet Vocoder Integration

### ISSUE THREAD

**Issue by imdatsolak** [Rayhane-mamah/Tacotron-2#2]
@Rayhane-mamah, I'm currently starting work on using a WaveNet based Vocoder to connect to Tacotron-2. Any pointers to your Tacotron-2 implementation to start with? I have a wavenet_vocoder implementation that could use Mel- or WAV-conditioning to generate audio. I would like to put a Mel as input to WaveNet and have then a final audio as output... Any recommendation would be appreciated. At the end, I want to make a parallel-wavenet out of it and then put back on GitHub. The point mainly is that you have, so far, not implemented a prediction code and I was wondering where the hook ...

**Comment by Rayhane-mamah** [comment]
Hi @imdatsolak, thank you for reaching out.

Like you said, we still haven't implemented the prediction part to link the two components and get the final Tacotron-2 Network. There are mainly two reasons for that:

1- We're still testing the concordance of the Feature prediction model we implemented with the one described in the paper
2- We're a bit short in time and computation power to move forward with the project right now, we're mainly putting it to sleep till next month, we're open however to consider fixing issues.

What you can try however, if you find it pleasant, is to try and train you vocoder using ground truth mel spectrograms. As mentioned in the paper, this will give slightly worse results than when using the direct predictions of the feature prediction model, but considering the training time wavenet can take to get perfect results, you can consider this approach.

There is actually a good wavenet vocoder [reference](https://github.com/r9y9/wavenet_vocoder) that had nice results and that is able to use local conditioning on mel spectrograms along with the logistic mixture distribution. It is written using Pytorch, and as I said earlier, we'll probably be converting it to tensorflow later next month. 

If there is anything else we can help you with, feel free to ask.

**Comment by imdatsolak** [comment]
Hi @Rayhane-mamah, thanks for the quick reply. In fact, I'm trying to use the referenced WaveNet Vocoder. So, I will try generating mel spectrograms from Tacotron to feed it to WaveNet Vocoder and see what we can come up with.
I have some computing power (3 machines, with 2x NVidia 1080 Ti each with NVME-SSDs and lots of RAM/CPU-Cores) to use. So far, I have trained the Vocoder and the initial (test-)results are actually quite good (using mel-spectrograms from testsets). I actually want to keep the Vocoder in PyTorch because it seems it is significantly more efficient on GPU-utilization and learning performance. I'll also try adding parallel WaveNet to it.

Anyway, thank you very much for the feedback. Any new update/change on Tacotron-2 will be (of course) sent to you.

Great work, btw, thanks again.

**Comment by Rayhane-mamah** [comment]
Thank you for your support @imdatsolak, we will inform you of any progress and as soon as we get our pre-trained feature prediction model up and running, we'll be glad to share it with you. (I'll be adding the prediction code soon enough, this week-end probably).

**Comment by Rayhane-mamah** [comment]
I can finally this has been done without errors :)
