### ISSUE TITLE
synthesis?

### ISSUE THREAD

**Issue by kst5118** [Rayhane-mamah/Tacotron-2#207]
Thank you @Rayhane-mamah for nice new repo.
There are so many big improvements.
Audio quality of linear wav in eval/wav is very very good.
But I got error like this when synthesizing.

![image](https://user-images.githubusercontent.com/43393764/45725144-55298980-bbf4-11e8-83db-f24fa45c3427.png)

Please help me to solve this error.

**Comment by tdplaza** [comment]
check plot_alignment() function in Plot.py to make sure it is declared like this:

def plot_alignment(alignment, path, **info=None**, split_title=False, max_len=None):
