### ISSUE TITLE
Tacotron + Wavenet for Lithuanian language synthesis.

### ISSUE THREAD

**Issue by aleksas** [Rayhane-mamah/Tacotron-2#215]
Trained Tacotron and wavenet (both HEAD rev) with speaker conditioning for Lituanian language. The results are great, taking into account that dataset is just ~4h for each of 4 speakers speaker (2 women, 2 men).

Experiment results are [HERE](https://aleksas.github.io/wavenet_vocoder_liepa/taco_wave_1.html#taco-120000-wave-360000--200000-fine-tuned). There are plenty of issues regarding word stressing (in Lithuanian it's far for trivial) and bad punctuation interpretation, but all of that is easily attributable to sub-optimal data-set size which is likely not covering all variations in significant amount if at all.

Thanks guys @r9y9, @Rayhane-mamah and all the other - great job.

**Comment by gsoul** [comment]
Could you please post schedules, hyperparameters parameters etc on how you achieved such results?

**Comment by aleksas** [comment]
Trained wavenet and Taco separetely. Links to specific repo revisions: [Wavenet](https://github.com/aleksas/wavenet_vocoder/tree/7c87267f2c53d2dd54cdb35157607a50053a7f69) and [Tacotron](https://github.com/aleksas/Tacotron-2/tree/d13dbba16f0a434843916b5a8647a42fe34544f5). 

- [Wavenet preset](https://github.com/aleksas/wavenet_vocoder/blob/master/presets/liepa_mixture.json)
- [Tacotron hparams](https://github.com/aleksas/Tacotron-2/blob/master/hparams.py)

**Comment by alexdemartos** [comment]
Hi @aleksas, good job! The sound quality is really good.

I would like to ask if you have trained separated Tacotron models for each speaker or if you have made some changes in order to train a joint multi-speaker model. If so, how did you do that?

Thanks!

**Comment by gsoul** [comment]
Did you use GTA for training wavenet?

**Comment by aleksas** [comment]
No, i did not. I first trained wavenet, then Tacotron. I guess using GTA would improve quality even more, but for now audio quality i've got is good enaugh.
