### ISSUE TITLE
Additional Training Data in French, Polish and Ukrainian

### ISSUE THREAD

**Issue by imdatsolak** [Rayhane-mamah/Tacotron-2#22]
Hi all,

today, we have added another 20 hrs to Ukrainian data set.  Also, we have added 53hrs of Polish.
Lastly, we have added 190hrs of French dataset, which should be available around 17:00h CEST on our server. Enjoy and have fun. French was a bit of a nightmare, but we think we have "conquered it" :)
All info and updates are on: http://www.m-ailabs.bayern/en/the-mailabs-speech-dataset/ website...

**Comment by pfriesch** [comment]
Nice dataset ! How did you do the alignment btw, by hand?

**Comment by Rayhane-mamah** [comment]
@imdatsolak great work! Looking forward to the finished version for French! wavs sound awesome!

**Comment by alex73** [comment]
@imdatsolak Is it possible to use your toolset for alignment ? I would like to prepare data for Belarusian language.

**Comment by Rayhane-mamah** [comment]
M-AILABS data is really great, I wonder why the website is down at the moment, hope this will get fixed soon..
