### ISSUE TITLE
Why is audio preprocessing different for Tacotron-2 and WaveNet?

### ISSUE THREAD

**Issue by alexdemartos** [Rayhane-mamah/Tacotron-2#222]
Hi, I am wondering why, for computing the mel spectogram of the audio, the following processing is done:

```
D = _stft(preemphasis(wav, hparams.preemphasis, hparams.preemphasize), hparams)
S = _amp_to_db(_linear_to_mel(np.abs(D), hparams), hparams) - hparams.ref_level_db

if hparams.signal_normalization:
  return _normalize(S, hparams)
return S
```

but when training the WaveNet, preemph and normalization is not applied on the audio output. I don't know about the preemph, but wouldn't we get better speech audio quality if audio is normalized and compressed also for training the WaveNet?

Thanks!

**Comment by tdplaza** [comment]
Me too, I do not know what's wavenet_preprocess used for.
