### ISSUE TITLE
cant train model after preprocessing

### ISSUE THREAD

**Issue by Suryansh5545** [Rayhane-mamah/Tacotron-2#231]
I cant train any model i have done preprocessing and have everything 

(tensorflow) F:\Tacotron-2-master\Tacotron-2-master>python train.py --model='Tacotron'
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 118, in main
    raise ValueError('please enter a valid model to train: {}'.format(accepted_models))
ValueError: please enter a valid model to train: ['Tacotron', 'WaveNet', 'Tacotron-2']

**Comment by tdplaza** [comment]
try using **--model=Tacotron** instead of **--model='Tacotron'**
