### ISSUE TITLE
system requirement

### ISSUE THREAD

**Issue by Suryansh5545** [Rayhane-mamah/Tacotron-2#233]
what is the miniumum requirenment to run tacotron i have i3 and 4gb ram.

**Comment by gsoul** [comment]
Depends on what you're trying to achieve. If just generation (inference) then perhaps your set-up might be fine. If you plan use that for training. That's not enough.

I'd think that you need at least 16GB of RAM and GPU with 11-12GB. Maybe GPU with 8GB might do, but I'm not sure.
