### ISSUE TITLE
How to freeze encoder and pretrain decoder?

### ISSUE THREAD

**Issue by cnlinxi** [Rayhane-mamah/Tacotron-2#244]
Hi, I want to freeze encoder and pretrain decoder, I get some errors when I add encoder_outputs_stop=tf.stop_gradient(encoder_outputs) in tacotron/models/tacotron.py.
Error:
Cannot convert a partially known TensorShape to a Tensor:(?,?)
How to fix it? Thanks a lot

**Comment by cnlinxi** [comment]
No. My teacher asked me to study something else. However, I'm still interested in this. Look forward to your solution.
I'm sorry for the late reply.

**Comment by cnlinxi** [comment]
> Hey, have you solved this problem ? Can u share with me your solution ?

No. My teacher asked me to study something else. However, I'm still interested in this. Look forward to your solution.
I'm sorry for the late reply.

**Comment by Clouxie** [comment]
Yup , as Rayhane told me, you should add new line "L123" in tacotron.py   
 encoder_outputs = tf.stop_gradient(encoder_outputs)
and also change placeholders (None) to hparams.tacotron_batch_size.
However it doesn't work for me. I've got .
ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.
Could you please re'open this task?

**Comment by Clouxie** [comment]
Yep, you should watch this one : https://github.com/Rayhane-mamah/Tacotron-2/issues/244
In my opinion 0.65h is too short, I could get aligment only with 2h oh data and more. The only good results I've noticed was near 1-2k steps. Even tho, I'm loosing too much language knowledge of model. I can't synthesize a bit longer audio, only short sentences. Please text me if u notice something interesting. I will investigate this more in my free time.
