### ISSUE TITLE
tabs vs spaces?

### ISSUE THREAD

**Issue by jyegerlehner** [Rayhane-mamah/Tacotron-2#25]
Is there a strong preference for the tabs over spaces? PEP8 [prefers spaces](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces). I guess most people's editors default to spaces.  Am I alone in preferring a switch over to spaces?

**Comment by Rayhane-mamah** [comment]
I actually prefer tabs to spaces, seems faster and easier..

Also, considering that my editor allows for easy manipulations with both and an easy conversion from one to the other, I can work with both easily.. Let's just say I got used to it?

I also have the tendency to use the 4-spaces tab not the 2-spaces.. Sorry for the trouble :)
