### ISSUE TITLE
Synthesize the same sentence twice but get different wavs

### ISSUE THREAD

**Issue by Yablon** [Rayhane-mamah/Tacotron-2#263]
I have trained a model with about 30h data. When synthesizing, I find that the same sentence may give different outputs via Tacotron. I didn't use WavNet and I didn't change any code inside. Do you have any experience about that? Or anywhere may cause random results?

**Comment by alexdemartos** [comment]
Hi Yablon,

this is due to dropout being applied not only when training but also at generation time.

**Comment by begeekmyfriend** [comment]
You may set drop out rate as 0 during inference time.

**Comment by Yablon** [comment]
> You may try setting drop out rate as 0 during inference time.

Thank you, that's very helpful.
