### ISSUE TITLE
seems gpu not been used

### ISSUE THREAD

**Issue by pandaGst** [Rayhane-mamah/Tacotron-2#271]
I run `python3 train.py --model='Tacotron'` with default parameters in hparams.py. But when I check GPU using with `nvidia-smi`, Gpu-Util is 0%.
 Is there any one got same question? 
Thank you very much!

**Comment by sid-sundrani** [comment]
Check out how to find the connected gpu devices on tensorflow- https://stackoverflow.com/questions/38009682/how-to-tell-if-tensorflow-is-using-gpu-acceleration-from-inside-python-shell. 

If the gpu device is not in there, make sure you have tensorflow-gpu installed

**Comment by pandaGst** [comment]
@sid-sundrani  Thank you very much!
 This issue troubled me few days.
I will try as your suggestion!

**Comment by mejanvijay** [comment]
Hi @pandaGst ! I am facing the same issue. Have you found a solution yet?

**Comment by pandaGst** [comment]
I changed some package's verson of my environment:
 tf-gpu==1.10
cuda==9.0
cudnn==7.1
anaconda==3
python==3.6.7

other packages version is same as requirment.txt gave.

Then it worked. 
But the capacity of gpu is not hight, just about 20%.

**Comment by mejanvijay** [comment]
Thanks. @pandaGst It worked for me as well now. I agree GPU utilization is really low.

**Comment by pandaGst** [comment]
This issue is inactive for a long time, close now. And reopen it if necessary.
