### ISSUE TITLE
G&L on GPU for speed up

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#287]
I have implemented [G&L on GPU](https://github.com/begeekmyfriend/Tacotron-2/blob/mandarin-new/tacotron/synthesizer.py#L39) on my own fork from yours. The modification is a bit large so I do not shoot a PR yet. In my test the speed of synthesis is much faster than that on CPU before. For roughly estimate **it generates 60 second speech in about 10 seconds,** not including the model loading time consuming. I think you'd better have a look at that and then decide whether you need to merge into your master branch.

**Comment by Rayhane-mamah** [comment]
Definitely useful, will probably merge it indeed. Great work! Thank you
very much for this contribution

**Comment by begeekmyfriend** [comment]
What settings? The settings are unchanged.

**Comment by QueenKeys** [comment]
> What settings? The settings are unchanged.

你好，您改写后的tacotron-griffin-lim版本，没有多GPU,在单GPU上训练的速度也是很快，但是有个问题需要请教您，tacotron_synthesis_batch_size这个参数在合成的时候，我发现无法以batch的方式将合成数据送入网络，这是怎么回事呢？希望得到您的恢复，谢谢

**Comment by begeekmyfriend** [comment]
@QueenKeys I failed with that too. If you want to synthesize in batch, you need to keep the input batch in the same length in time steps aka padding. But I still did not make it.
