### ISSUE TITLE
Why there is no prenet for encoder in T2?

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#288]
Prenet, in Tacotron paper, is described as a bottleneck for input precessing and it plays an important role for feature extraction right? In T1 we can see that there are both prenets for encoder and decoder inputs. I wonder why in T2 there is just decoder prenet and the encoder prenet is replaced by 3-layer convolution and oneout LSTM.

Now I am doing some experiments for this issue. I am replacing encoder convolution and LSTM with 2-layer prenet and CBHG just as T1 did. Let us wait and see what would happen in my test.
```python
#Encoder Cell ==> [batch_size, encoder_steps, encoder_lstm_units]
# encoder_cell = TacotronEncoderCell(
#       EncoderConvolutions(is_training, hparams=hp, scope='encoder_convolutions'),
#       EncoderRNN(is_training, size=hp.encoder_lstm_units,
#               zoneout=hp.tacotron_zoneout_rate, scope='encoder_LSTM'))

# encoder_outputs = encoder_cell(embedded_inputs, input_lengths)

#For shape visualization purpose
# enc_conv_output_shape = encoder_cell.conv_output_shape

prenet = Prenet(is_training, layers_sizes=hp.prenet_layers, drop_rate=hp.tacotron_dropout_rate, scope='encoder_prenet')
encoder_outputs = encoder_cbhg(prenet(embedded_inputs), input_lengths, is_training, hp.encoder_lstm_units)
```

**Comment by Rayhane-mamah** [comment]
Hey,

I already asked the same question and made the experiment. They both give
about the same result, but T2 approach is faster in terms of computation as
CBHG is pretty slow.

It would be interesting to see what you find tho, looking forward to it.

**Comment by begeekmyfriend** [comment]
In fact I am using some bad quality corpus for testing where the bad quality means that among all the training wav clips the voices seem **not quite unified**. See what happened to me? As for T1 it got alignment before 20K steps and for T2 it failed even at 200K steps. I am not blaming your project since for good corpus the evaluation from T2 sounds much better than T1. What I mean is that there seems more regularization items added in T2 and therefore it makes it harder to train for some bad corpus while it still gets alignment in T1. So I decide to switch respective modules between your T2 and Keith Ito's to find out the turning point where T2 works but T1 fails. It is still under testing and I will report the results at that time.

**Comment by begeekmyfriend** [comment]
Hey I removed both encoder convolution and LSTM and postnet (decoder convolution and LSTM) and replaced them with both prenet and CBHG. It began to get alignment at 16K steps for my **bad** corpus. The evalutation is still under testing and I will show you in the future.

I noticed you have added decoder CBHG after postnet for better linear spectrogram prediction. But I think it might be redundant with postnet. And therefore it might be hard for some corpus to get alignment. Would you like to consider selecting one of the two modules and remove the other?
![step-16000-align](https://user-images.githubusercontent.com/6031938/49348524-e632db80-f6e0-11e8-91b0-18f95668d879.png)

**Comment by xinqipony** [comment]
@begeekmyfriend  any further updates of the comparing?

**Comment by begeekmyfriend** [comment]
@xinqipony Nothing differences, closed.
