### ISSUE TITLE
Trying inherit Bahdanau monotonic attention for location sensitive attention but loss exploded

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#291]
@Rayhane-mamah I am trying `BahdanauMonotonicAttention` as super class over location sensitive attention. I just replace the original `BahdanauAttention` with `BahdanauMonotonicAttention` and removing `probability_fn` parameter in the `__init__` method. And the program began to run. However it quickly quited as an exception has been raised showing LOSS EXPLODED. I have no idea about it. Would you please do me a favor with it? Many thanks.

```shell
Tacotron training set to a maximum of 200000 steps
No model to load at logs-Tacotron/taco_pretrained

Generated 32 test batches of size 32 in 2.986 sec

Generated 32 train batches of size 32 in 3.032 sec
Loss exploded to nan at step 1 loss=nan, avg_loss=nan]
Exiting due to exception: Loss exploded
Traceback (most recent call last):
  File "/home/leoma/Tacotron-2/tacotron/train.py", line 184, in train
    raise Exception('Loss exploded')
Exception: Loss exploded
```

**Comment by MlWoo** [comment]
@begeekmyfriend I think the locative sensitive attention could capture the locality. But monotonic attention  also has the same feature which could maybe confict with the original code. Have you tried to replace the location sensitive attention with monotonic attention throughly?

**Comment by begeekmyfriend** [comment]
Not yet. I want to do that just because some **bad** corpus can not be aligned in this project. So I tried but  not made any progress currenly.

**Comment by fastcode3d** [comment]
@begeekmyfriend Have you solved this problem? I met the same problem.

**Comment by begeekmyfriend** [comment]
Meanless because it has been implemented in the latest version. Closing it.
