### ISSUE TITLE
hyperparam "min_level_db" default value issue

### ISSUE THREAD

**Issue by min8328** [Rayhane-mamah/Tacotron-2#293]
Hi, I have found difference between default value of min_level_db and the comment about this in the paper.

In Section 2.2 Paragraph 2 of Tacotron2 paper,
"Prior to log compression, the filterbank output magnitudes are clipped to a minimum value of 0.01 in order to limit dynamic range in the logarithmic domain."

but in the corresponding part of datasets/audio.py is like,
def _amp_to_db(x, hparams):
	min_level = np.exp(hparams.min_level_db / 20 * np.log(10))
	return 20 * np.log10(np.maximum(min_level, x))

and in hparam.py, the default value of min_level_db is shown as below,
	#Limits
	min_level_db = -100,

It supposed to be -40 for keeping consistency with paper, right?
Or is this issue not a big deal for performance or stability?
I really appreciated for reviewing my concern in advance.

**Comment by Rayhane-mamah** [comment]
Hi thanks for reaching out.

I have tried both and found that current setup works best (around 0.11
minimal bound).
The audio preprocessing params largely sepend on your data, default are
optimized for LJspeech dataset, so please adapt as you like for your own
dataset.
If you want consistency with the paper, switch np.exp with 10**, np.log
with np.log10 and min_level_db to -40 in min_level computation.
That will make your lower bound 0.01.

If you do try other options, feel free to share your results :)

**Comment by min8328** [comment]
I see. I'll try what you said. Thank you. :)
