### ISSUE TITLE
Same input get different results, some results are invalid

### ISSUE THREAD

**Issue by Yablon** [Rayhane-mamah/Tacotron-2#296]
Hi, everyone. I asked a question about same inputs getting different results 20 days ago. 
Some friends told me to change drop out rate to 0 to solve my previous question. That works actually.

But I find another question occasionly. If I give an unique input sentence, and synthesize it for many times,  there is a possibility that some outputs are definitely not what you want, neither can you recognize what it is speaking.

I checked the number of output frames of Tacotron, finding that the frames changes from time to time. Those too large or too small can't lead to understandable results.

Can you synthesize a sentence for many times to check that out ? And does anyone have an answer to that ? Thank you for resolving my doubt of many days. I like this place.

**Comment by begeekmyfriend** [comment]
```python
dropout_rate = 0.5 if is_training else 0
``

**Comment by Yablon** [comment]
@begeekmyfriend thank you for answering my stupid questions!
