### ISSUE TITLE
what's the f?

### ISSUE THREAD

**Issue by zhf459** [Rayhane-mamah/Tacotron-2#3]
https://github.com/Rayhane-mamah/Tacotron-2/blob/de5e151e8568fc052de0455731cf7f12e4c3a11a/tacotron/models/helpers.py#L44
hi ,is this seems a bug?where the f come from?how to predict mel outputs when given a sentence?

**Comment by Rayhane-mamah** [comment]
You're right that file isn't up to date, i'll come back to you on that
tonight and i'll be adding the prediction part short enough. Thanks for
reaching out.

**Comment by Rayhane-mamah** [comment]
I updated the helpers file and added the synthesis code. Although we are not entirely sure of the performance of the stop token prediction, as it fails sometimes to efficiently choose when to end and goes all the way to the max decoder steps.

If you notice any other issue feel free to report, we'll get right to it.
