### ISSUE TITLE
New Features: Speaker Embedding & GST

### ISSUE THREAD

**Issue by ErnstTmp** [Rayhane-mamah/Tacotron-2#308]
@Rayhane-mamah  in another issue you mentioned speaker embedding - are you working on this, or could you need help? I talked to Daisy Stanton from Google at SLT 2018, and she mentioned if training multi-speaker datasets, one needs a speaker embedding, including an unknown speaker.

Also, I would be interested in GST - Global Style Tokens (see https://arxiv.org/abs/1803.09017). Have you thought of implementing this, or is help needed .-))

Thanks for creating this!!!!!!

**Comment by ErnstTmp** [comment]
Thank you very much for your very fast feedback and the confirmation that these items work! 

I will try to implement them.

When I discussed Tacotron issues with Daisy Stanton from Google, she mentioned that GMM attention is best and definitely necessary for GST to work. Can you comment on that? Is the attention used in T2 sufficient?

Thank you so much for open sourcing the T2!!!

**Comment by Rayhane-mamah** [comment]
Hi again,

I didn't really try out GMM so I can't for sure give my opinion on that.
However, I did try both vanilla Bahdanau (content) attention and T2 location sensitive. I definitely found that T2 attention worked better in my experiments.

Overall, one can mix features from multiple similar Encoder-Decoder architectures to Tacotron, it can show good results. GMM attention may be one of these improvements.

Thanks for your support.

**Comment by ErnstTmp** [comment]
Thanks  a lot for your opinion, that is very valuable to me!!! So I do not need to implement GMM Attention. That would have been quite hard :-))

Kind regards
Ernst

**Comment by sandipjedhe** [comment]
@ErnstTmp  and @Rayhane-mamah  Is anyone combined tacotron2 and gst

**Comment by cnlinxi** [comment]
@sandipjedhe @ErnstTmp hi, I combine Tacotron2 & gst based on Rayhane Tacotron: https://github.com/cnlinxi/style-token_tacotron2. I successfully get different style on Chinese. You can try it on other language:)

**Comment by begeekmyfriend** [comment]
@cnlinxi What kind of dataset did you train? With single speaker or multi-speakers?

**Comment by cnlinxi** [comment]
I train it on THCHS-30. I don't have a better dataset.

**Comment by begeekmyfriend** [comment]
@cnlinxi I have tried biaobei open Chinese corpus with single speaker but it failed to transfer within different styles. It shows that we have to train with multi-speakers corpus https://github.com/KinglittleQ/GST-Tacotron/issues/6

**Comment by cnlinxi** [comment]
@begeekmyfriend yes, biaobei open Chinese corpus is single speaker and too bland. We look forward to better corpus:(

**Comment by maelp** [comment]
@Rayhane-mamah could you tell if the speaker-embedding you did was only concatenated to the encoder output, or did you also need to add the speaker-embedding to the encoder input? For now, after a few thousand steps, it seems that the model does not generate multiple speakers when I train it on LibriTTS (I did a simple embedding and concatenated it to the encoder output at each timestep)

**Comment by m-toman** [comment]
@maelp nice to see you ;)
The implementation here works quite well
https://github.com/CorentinJ/Real-Time-Voice-Cloning/tree/master/synthesizer

**Comment by maelp** [comment]
Hi @m-toman :) I saw that implementation, and I used a code which is equivalent, but I'm learning the speaker-embedding while training Tacotron and not on another task, and I'm wondering if this is sufficient to get multi-speaker outputs. Right now it seems that all the data generated during `python synthesize` has the "same speaker" sound, but perhaps it is because it should train for a few more steps
