### ISSUE TITLE
about background noises

### ISSUE THREAD

**Issue by XiaooaiX** [Rayhane-mamah/Tacotron-2#312]
I have tried several dataset, and found that the quality of mel spectrum is not good enough, can u post some of your trained sample wav files?

Thanks!

**Comment by begeekmyfriend** [comment]
You might try linear spectrograms through G&L synthesizer.

**Comment by XiaooaiX** [comment]
> You might try linear spectrograms through G&L synthesizer.

Have you tried this repo on some datasets? How does it works?
I have trained this model for over 100k steps but found there is always some background noises for every dataset. Yep I used grifflim for vocoder, however I don't think the background noises is due to the vocoder. When I trained the datasets using taco1, there is no problem about that even if I use grifflim. 
If you could post up ur trained wav files, that could be better.

**Comment by begeekmyfriend** [comment]
https://github.com/Rayhane-mamah/Tacotron-2/issues/292
If my [fork](https://github.com/begeekmyfriend/Tacotron-2) does not work for you, then it might well be the issue of your corpus.

**Comment by XiaooaiX** [comment]
> #292
> If my [fork](https://github.com/begeekmyfriend/Tacotron-2) does not work for you, then it might well be the issue of your corpus.

.wav file results, please! only words make non sense... I'd like to check if it's my problems or it's because the code itself... Your training results will help. However, the results you presented here is not good either...

**Comment by begeekmyfriend** [comment]
Didn't you see them?

**Comment by XiaooaiX** [comment]
> Didn't you see them?

https://rayhane-mamah.github.io/Tacotron-2_audio_samples/
this one? I listened to it for a second time, it doesn't has background noises. Emmm do u have samples with more steps?  It's weird that my two trained datasets both have background noises and don't know why... but if I use the taco1 repos it will be ok. Have struggled on this for days..  Do u have some ideas about that and have u encountered with such kind of problems?
Thanks!

**Comment by begeekmyfriend** [comment]
The link on the last floor https://github.com/Rayhane-mamah/Tacotron-2/issues/292#issuecomment-444823633 and the another on the 2nd floor https://github.com/Rayhane-mamah/Tacotron-2/issues/304#issuecomment-450314638

**Comment by begeekmyfriend** [comment]
The link on the last floor https://github.com/Rayhane-mamah/Tacotron-2/issues/292#issuecomment-444823633 and another on the 12th floor https://github.com/keithito/tacotron/issues/241#issuecomment-450775451

**Comment by XiaooaiX** [comment]
Have solved the problem, the model itself works fine. Thank you guys very much for the contribution! 

Cheers!

**Comment by NewEricWang** [comment]
@XiaooaiX , How did you solve the problem? Could you give me some help?

**Comment by WhiteFu** [comment]
> Have solved the problem, the model itself works fine. Thank you guys very much for the contribution!
> 
> Cheers!

How did you remove the background noise? Could you give me some help?
