### ISSUE TITLE
Exception thrown on Speaker adaptation parameter

### ISSUE THREAD

**Issue by Tacotronuser** [Rayhane-mamah/Tacotron-2#320]
I got the following error when i enable the fine tuning parameter in hyparams. i have trained the 70k steps on LJ data and now i want to do my speaker adaption. following exception is thrown when i run training:

Initialized Tacotron model. Dimensions (? = dynamic shape): 
  Train mode:               True
  Eval mode:                False
  GTA mode:                 False
  Synthesis mode:           False
  Input:                    (?, ?)
  device:                   0
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out:              (?, ?, 512)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  linear out:               (?, ?, 1025)
  <stop_token> out:         (?, ?)
  Tacotron Parameters       29.016 Million.
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    main()
  File "train.py", line 132, in main
    train(args, log_dir, hparams)
  File "train.py", line 52, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "/home/////Tacotran_2/Tacotron-2/tacotron/train.py", line 375, in tacotron_train
    return train(log_dir, args, hparams)
  File "/home/////Tacotran_2/Tacotron-2/tacotron/train.py", line 156, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "//////Tacotran_2/Tacotron-2/tacotron/train.py", line 93, in model_train_mode
    model.add_optimizer(global_step)
  File "//////Tacotran_2/Tacotron-2/tacotron/models/tacotron.py", line 390, in add_optimizer
    update_vars = [v for v in self.all_vars if not ('inputs_embedding' in v or 'encoder_' in v)] if hp.tacotron_fine_tuning else None
  File "//////Tacotran_2/Tacotron-2/tacotron/models/tacotron.py", line 390, in <listcomp>
    update_vars = [v for v in self.all_vars if not ('inputs_embedding' in v or 'encoder_' in v)] if hp.tacotron_fine_tuning else None
TypeError: argument of type 'Variable' is not iterable

I set only following to true from false:
#Speaker adaptation parameters
	tacotron_fine_tuning = True, #Set to True to freeze encoder and only keep training pretrained decoder. Used for speaker adaptation with small data.
	###########################################################################################################################################

**Comment by Rayhane-mamah** [comment]
Hi, this is fixed in latest commits, please update your cloned repo

**Comment by Tacotronuser** [comment]
Thanks for sharing, yes exception is fixed.

But i have an issue that when i run with tacotron_fine_tuning = True, the wavenet model training started with negative loss and its not giving good results, very very poor results. 

please suggest.
