### ISSUE TITLE
(Preprocessing) Shouldn't hparams.clip_mels_length trim the audio length instead of pruning the sample?

### ISSUE THREAD

**Issue by CorentinJ** [Rayhane-mamah/Tacotron-2#326]
In datasets/preprocessor.py, at line 120:
```
	if mel_frames > hparams.max_mel_frames and hparams.clip_mels_length:
		return None
```
Samples are discarded if they are longer than `hparams.max_mel_frames`. Is this intended? Shouldn't the audio just be trimmed to `hparams.max_mel_frames` instead? The only reason why I can see this being a problem is because the audio would be cut abruptly.

**Comment by m-toman** [comment]
The main issue (imho) would be the resulting mismatch with the transcription.

**Comment by CorentinJ** [comment]
You're right. Maybe that is one reason why ASR is used to align speech with the text in the Tacotron2 paper.
