### ISSUE TITLE
The pitch will be lost since it is below the threshold of fmin in hparam

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#33]
I have noticed that the `fmin` in `hparam.py` is set as 125Hz that is above the general value of pitch 100Hz. My colleague says that the pitch will be lost in mel filter banks if the frequency bank does not include 100Hz. He suggest the `fmin` be set as 50 or 75.

**Comment by Rayhane-mamah** [comment]
Hello @begeekmyfriend!

hmmm yeah you might be right.. One thing I'm sure of is that for females, pitch is higher than 100Hz, for males this can be problematic.. So as a solution I guess you can set fmin to 0 for now :) 

Feel free to share results if there are any improvements. Thank you very much for reporting this.

**Comment by Rayhane-mamah** [comment]
By the way, I tried few stuff recently and 0 really tends to be noisy.. fmin=75 should be good for males while 125 is a good value for females I guess.

Of course this will have to be adapted to the data at hand in the end.

**Comment by gloriouskilka** [comment]
I tried fmin 75, trained a bit with it, but when generaied samples, noticed that pitch of the speaker was too high. Switched fmin back to 0, rerun generation and it generated ok.

**Comment by Rayhane-mamah** [comment]
@gloriouskilka, you're right, my bad again :)

I actually preprocessed using a value of fmin and was inverting using another one, which led to catastrophic results.. I for my part find no big difference in ground truth whether created with 125 or 0 minimal frequency. (For Ljspeech). Here's a sample ground truth mel generated using fmin=125 then fmin=0. Exact same...

![plot](https://user-images.githubusercontent.com/34689728/39539448-8e588d26-4e37-11e8-8b1b-6c12d17d7c5a.png)

![plots](https://user-images.githubusercontent.com/34689728/39539455-944ed848-4e37-11e8-8045-684597e00335.png)



I am however currently trying something that might make the model generate inverted audio very similar to inverted ground truth mels. I will tell you how it goes and share the method if it works.

**Comment by HallidayReadyOne** [comment]
@Rayhane-mamah    “I am however currently trying something that might make the model generate inverted audio very similar to inverted ground truth mels. I will tell you how it goes and share the method if it works.”    Is the method GAN?
