### ISSUE TITLE
Alignment off for particular dataset

### ISSUE THREAD

**Issue by ZohaibAhmed** [Rayhane-mamah/Tacotron-2#365]
I have a model trained on LJ for 200k steps, and then I fine-tune a smaller dataset on top. So far I've had success with a couple of datasets (male and female) for data that ranges 15-30 minutes in length.

I have another dataset that is about 60 minutes in length, but the alignment is off. The dataset contains the same sentences said by a different speaker.

Here's the alignment for the speaker that works:

![image](https://user-images.githubusercontent.com/660224/55585771-6e5bd880-56f5-11e9-94bd-7bd815d6b36a.png)

Here's the one that doesn't:

![image](https://user-images.githubusercontent.com/660224/55585803-7ca9f480-56f5-11e9-952a-ead13c724c09.png)

Both files have the same metadata:

```
Input File     : '150.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:02.82 = 45120 samples ~ 211.5 CDDA sectors
File Size      : 90.3k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```

This is a sample melspectrogram from the dataset:

![image](https://user-images.githubusercontent.com/660224/55582294-1e791380-56ed-11e9-9f8c-7836cd78885b.png)

In my case, the model was trained with `r=1`, batch_size=32. 

So far, I've looked at the dataset to see if there are any distinguishable factors. I've cleaned the audio dataset with `sox` to reduce noise, but that doesn't seem to make a difference. Any pointers would be appreciated.

**Comment by RoelVdP** [comment]
@ZohaibAhmed out of interest, what version of Python and libs (just requirements.txt?) do you use? Any modified settings in hparams? Also, do you use a GPU? I am struggling to get the LJ dataset to work. Training 4000 steps and then synthesizing gives mumble jumble output.

**Comment by ZohaibAhmed** [comment]
@RoelVdP - just requirements.txt. If you're using the latest numpy, make sure you update librosa to 0.6.3. 

No real modifications to the hparams are needed. I am training on GPUs, so your mileage may vary.  As mentioned in other issues, you can tweak the batch_size and outputs_per_step in hparams if you have a smaller GPU. Training on CPU is not recommended.

You'll have to train it for quite a bit to start to get good results. I can't remember the exact mark, but ~30k steps seems to be start improving.

**Comment by NewEricWang** [comment]
@ZohaibAhmed , what does r=1 mean in Tacotron-2? Which parameter does it correspond to in hparams?
