### ISSUE TITLE
Running on tensorflow-serving

### ISSUE THREAD

**Issue by n5-suzuki** [Rayhane-mamah/Tacotron-2#394]
I want to run on trained-models on tensorflow-serving.
Though I could save as pb-model by SavedModelBuilder, I couldn't run on tensorflow-serving with following message.
<hr>
E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: *** version: 1} failed: Invalid argument: No OpKernel was registered to support Op 'PyFunc' used by {{node Tacotron_model/PyFunc}}with these attrs: [token="pyfunc_0", _output_shapes=[<unknown>], Tin=[DT_INT32, DT_INT32], Tout=[DT_INT32]]
<hr>
This message maybe express  which is 'tf.py_func' in tacotron/models/tacotron.py
How can I rewrite the code without 'tf.py_func'?

Thank you!

**Comment by n5-suzuki** [comment]
solved!

**Comment by wsr692** [comment]
can you share how you solved this issue?

**Comment by emmacirl** [comment]
+1

**Comment by salanki** [comment]
Yes, can you please share how you exported this?

**Comment by offbye** [comment]
can u share the export savedmodel code？
