### ISSUE TITLE
Tensorflow 2

### ISSUE THREAD

**Issue by njellinas** [Rayhane-mamah/Tacotron-2#455]
Hello, does anyone has any idea of how this would be implemented in Tensorflow 2?
They have introduced this tensorflow-addons, but I tried with all the tf.function stuff and there was always an impassable error :P

**Comment by kevastator** [comment]
I have attempted to use Tf2, but it doesn't seem to work with preprocessed data.

**Comment by dathudeptrai** [comment]
here in my TF2 implementation: https://github.com/dathudeptrai/TensorflowTTS. @njellinas @kevastator
