### ISSUE TITLE
Mel normalization

### ISSUE THREAD

**Issue by sharathadavanne** [Rayhane-mamah/Tacotron-2#458]
Hi @Rayhane-mamah regarding the mel-features normalization in the [-4, 4] range, I was wondering why this range? and why not the usual zero-mean unit-variance range of [-1 1]? Any insight would be helpful.

**Comment by JasonWei512** [comment]
"I mainly scale to [-4, 4] to enable for more detail in the output mel spectrogram (in the model's vision). Purely based on experience, outputs scaled to large domains tend to make T2 converge faster and better.."

https://github.com/Rayhane-mamah/Tacotron-2/issues/29

**Comment by sharathadavanne** [comment]
Thanks for the quick answer
