### ISSUE TITLE
No such file or directory: 'tacotron_ouptut\\gta\map.txt

### ISSUE THREAD

**Issue by graham-eisele** [Rayhane-mamah/Tacotron-2#466]
After changing the data for fine-tuning and running the preprocess script on the new data set and running train. I get an error: No such file or directory: 'tacotron_ouptut\\gta\map.txt, and was wondering does it not create it automatically during preprocess or train.py? and if so how to make it or fix it.

**Comment by AwaisKhan5647** [comment]
i am getting the same issue tell me the solution please
and i am not executing the wavenet preprocessing is it need to be done before wavenet training?
