### ISSUE TITLE
Problems on Chinese mandarin using latest model

### ISSUE THREAD

**Issue by switchzts** [Rayhane-mamah/Tacotron-2#53]
Hi, Rayhane-mamah,
Thanks for sharing the code. 
I have some problems on it,can you give some advices?
I found that when I used tocatron_batch_size = 32 outputs_per_step = 1,(use "Both")my traning rate is about 7 sec/step. It is normal?It means it will take about 622 hours to reach 320k, which is defalut steps limit.I found in issues 18 that @begeekmyfriend used old model and rate is about 1sec/step,which I think it is comfortable.I didn't change your parameters except use predict_linear = True,sample_rate and cleaners,I use a professional P40 card, It used about 16G of memory,so it shouldn't be a problem.May I ask you about the speed of your model when you are traning?
Look forward to your feedback

**Comment by switchzts** [comment]
`# Comma-separated list of cleaners to run on text prior to training and eval. For non-English
	# text, you may want to use "basic_cleaners" or "transliteration_cleaners".
	cleaners='basic_cleaners',

	#Hardware setup (TODO: multi-GPU parallel tacotron training)
	use_all_gpus = False, #Whether to use all GPU resources. If True, total number of available gpus will override num_gpus.
	num_gpus = 1, #Determines the number of gpus in use
	###########################################################################################################################################

	#Audio
	num_mels = 80, #Number of mel-spectrogram channels and local conditioning dimensionality
	num_freq = 513, #only used when adding linear spectrograms post processing network
	rescale = True, #Whether to rescale audio prior to preprocessing
	rescaling_max = 0.999, #Rescaling value
	trim_silence = True, #Whether to clip silence in Audio (at beginning and end of audio only, not the middle)
	clip_mels_length = True, #For cases of OOM (Not really recommended, working on a workaround)
	max_mel_frames = 900,  #Only relevant when clip_mels_length = True

	# Use LWS (https://github.com/Jonathan-LeRoux/lws) for STFT and phase reconstruction
	# It's preferred to set True to use with https://github.com/r9y9/wavenet_vocoder
	use_lws=True,
	silence_threshold=2, #silence threshold used for sound trimming for wavenet preprocessing

	#Mel spectrogram
	fft_size = 1024,
	hop_size = 256,
	sample_rate = 16000, #22050 Hz (corresponding to ljspeech dataset)
	frame_shift_ms = None,

	#Mel and Linear spectrograms normalization/scaling and clipping
	signal_normalization = True,
	allow_clipping_in_normalization = True, #Only relevant if mel_normalization = True
	symmetric_mels = True, #Whether to scale the data to be symmetric around 0
	max_abs_value = 4., #max absolute value of data. If symmetric, data will be [-max, max] else [0, max] 

	#Limits
	min_level_db =- 100,
	ref_level_db = 20,
	fmin = 75, #Set this to 75 if your speaker is male! if female, 125 should help taking off noise. (To test depending on dataset)
	fmax = 7600, 

	#Griffin Lim
	power = 1.2, 
	griffin_lim_iters = 60,
	###########################################################################################################################################

	#Tacotron
	outputs_per_step = 1, #number of frames to generate at each decoding step (speeds up computation and allows for higher batch size)
	stop_at_any = True, #Determines whether the decoder should stop when predicting <stop> to any frame or to all of them

	embedding_dim = 512, #dimension of embedding space

	enc_conv_num_layers = 3, #number of encoder convolutional layers
	enc_conv_kernel_size = (5, ), #size of encoder convolution filters for each layer
	enc_conv_channels = 512, #number of encoder convolutions filters for each layer
	encoder_lstm_units = 256, #number of lstm units for each direction (forward and backward)

	smoothing = False, #Whether to smooth the attention normalization function 
	attention_dim = 128, #dimension of attention space
	attention_filters = 32, #number of attention convolution filters
	attention_kernel = (31, ), #kernel size of attention convolution
	cumulative_weights = True, #Whether to cumulate (sum) all previous attention weights or simply feed previous weights (Recommended: True)

	prenet_layers = [256, 256], #number of layers and number of units of prenet
	decoder_layers = 2, #number of decoder lstm layers
	decoder_lstm_units = 1024, #number of decoder lstm units on each layer
	max_iters = 2500, #Max decoder steps during inference (Just for safety from infinite loop cases)

	postnet_num_layers = 5, #number of postnet convolutional layers
	postnet_kernel_size = (5, ), #size of postnet convolution filters for each layer
	postnet_channels = 512, #number of postnet convolution filters for each layer

	mask_encoder = True, #whether to mask encoder padding while computing attention
	mask_decoder = True, #Whether to use loss mask for padded sequences (if False, <stop_token> loss function will not be weighted, else recommended pos_weight = 20)

	cross_entropy_pos_weight = 20, #Use class weights to reduce the stop token classes imbalance (by adding more penalty on False Negatives (FN)) (1 = disabled)
	predict_linear = True, #Whether to add a post-processing network to the Tacotron to predict linear spectrograms (True mode Not tested!!)
	###########################################################################################################################################


	#Wavenet
	# Input type:
	# 1. raw [-1, 1]
	# 2. mulaw [-1, 1]
	# 3. mulaw-quantize [0, mu]
	# If input_type is raw or mulaw, network assumes scalar input and
	# discretized mixture of logistic distributions output, otherwise one-hot
	# input and softmax output are assumed.
	input_type="raw",
	quantize_channels=65536,  # 65536 (raw) or 256 (mulaw or mulaw-quantize) // number of classes = 256 <=> mu = 255

	log_scale_min=float(np.log(1e-14)), #Mixture of logistic distributions minimal log scale

	out_channels = 10 * 3, #This should be equal to quantize channels when input type is 'mulaw-quantize' else: num_distributions * 3 (prob, mean, log_scale)
	layers = 24, #Number of dilated convolutions (Default: Simplified Wavenet of Tacotron-2 paper)
	stacks = 4, #Number of dilated convolution stacks (Default: Simplified Wavenet of Tacotron-2 paper)
	residual_channels = 512,
	gate_channels = 512, #split in 2 in gated convolutions
	skip_out_channels = 256,
	kernel_size = 3,

	cin_channels = 80, #Set this to -1 to disable local conditioning, else it must be equal to num_mels!!
	upsample_conditional_features = True, #Whether to repeat conditional features or upsample them (The latter is recommended)
	upsample_scales = [16, 16], #prod(scales) should be equal to hop size
	freq_axis_kernel_size = 3,

	gin_channels = -1, #Set this to -1 to disable global conditioning, Only used for multi speaker dataset
	use_bias = True, #Whether to use bias in convolutional layers of the Wavenet

	max_time_sec = None,
	max_time_steps = 13000, #Max time steps in audio used to train wavenet (decrease to save memory)
	###########################################################################################################################################

	#Tacotron Training
	tacotron_random_seed = 5339, #Determines initial graph and operations (i.e: model) random state for reproducibility
	tacotron_swap_with_cpu = False, #Whether to use cpu as support to gpu for decoder computation (Not recommended: may cause major slowdowns! Only use when critical!)

	tacotron_batch_size = 32, #number of training samples on each training steps
	tacotron_reg_weight = 1e-6, #regularization weight (for l2 regularization)
	tacotron_scale_regularization = False, #Whether to rescale regularization weight to adapt for outputs range (used when reg_weight is high and biasing the model)

	tacotron_test_size = None, #% of data to keep as test data, if None, tacotron_test_batches must be not None
	tacotron_test_batches = 48, #number of test batches (For Ljspeech: 10% ~= 41 batches of 32 samples)
	tacotron_data_random_state=1234, #random state for train test split repeatability

	tacotron_decay_learning_rate = True, #boolean, determines if the learning rate will follow an exponential decay
	tacotron_start_decay = 10000, #Step at which learning decay starts
	tacotron_decay_steps = 10000, #Determines the learning rate decay slope (UNDER TEST)
	tacotron_decay_rate = 0.33, #learning rate decay rate (UNDER TEST)
	tacotron_initial_learning_rate = 1e-3, #starting learning rate
	tacotron_final_learning_rate = 1e-5, #minimal learning rate

	tacotron_adam_beta1 = 0.9, #AdamOptimizer beta1 parameter
	tacotron_adam_beta2 = 0.999, #AdamOptimizer beta2 parameter
	tacotron_adam_epsilon = 1e-6, #AdamOptimizer beta3 parameter

	tacotron_zoneout_rate = 0.1, #zoneout rate for all LSTM cells in the network
	tacotron_dropout_rate = 0.5, #dropout rate for all convolutional layers + prenet
	
	natural_eval = True, #Whether to use 100% natural eval (to evaluate Curriculum Learning performance) or with same teacher-forcing ratio as training (just for overfit)

	#Decoder RNN learning can take be done in one of two ways:
	#	Teacher Forcing: vanilla teacher forcing (usually with ratio = 1). mode='constant'
	#	Curriculum Learning Scheme: From Teacher-Forcing to sampling from previous outputs is function of global step. (teacher forcing ratio decay) mode='scheduled'
	#The second approach is inspired by:
	#Bengio et al. 2015: Scheduled Sampling for Sequence Prediction with Recurrent Neural Networks.
	#Can be found under: https://arxiv.org/pdf/1506.03099.pdf
	tacotron_teacher_forcing_mode = 'constant', #Can be ('constant' or 'scheduled'). 'scheduled' mode applies a cosine teacher forcing ratio decay. (Preference: scheduled)
	tacotron_teacher_forcing_ratio = 1., #Value from [0., 1.], 0.=0%, 1.=100%, determines the % of times we force next decoder inputs, Only relevant if mode='constant'
	tacotron_teacher_forcing_init_ratio = 1., #initial teacher forcing ratio. Relevant if mode='scheduled'
	tacotron_teacher_forcing_final_ratio = 0., #final teacher forcing ratio. Relevant if mode='scheduled'
	tacotron_teacher_forcing_start_decay = 10000, #starting point of teacher forcing ratio decay. Relevant if mode='scheduled'
	tacotron_teacher_forcing_decay_steps = 220000, #Determines the teacher forcing ratio decay slope. Relevant if mode='scheduled'
	tacotron_teacher_forcing_decay_alpha = 0., #teacher forcing ratio decay rate. Relevant if mode='scheduled'
	###########################################################################################################################################

	#Wavenet Training
	wavenet_random_seed = 5339, # S=5, E=3, D=9 :)
	wavenet_swap_with_cpu = False, #Whether to use cpu as support to gpu for decoder computation (Not recommended: may cause major slowdowns! Only use when critical!)

	wavenet_batch_size = 4, #batch size used to train wavenet.
	wavenet_test_size = 0.0441, #% of data to keep as test data, if None, wavenet_test_batches must be not None
	wavenet_test_batches = None, #number of test batches.
	wavenet_data_random_state = 1234, #random state for train test split repeatability

	wavenet_learning_rate = 1e-4,
	wavenet_adam_beta1 = 0.9,
	wavenet_adam_beta2 = 0.999,
	wavenet_adam_epsilon = 1e-6,

	wavenet_ema_decay = 0.9999, #decay rate of exponential moving average

	wavenet_dropout = 0.05, #drop rate of wavenet layers
	train_with_GTA = False, #Whether to use GTA mels to train WaveNet instead of ground truth mels.
	###########################################################################################################################################
`

**Comment by Rayhane-mamah** [comment]
Hello @switchzts, thanks for reaching out.

First, no I am disabling linear predictions for GTA synthesis, assuming GTA synthesis will only be used to generate mels for training Wavenet. Do you want to synthesize linear with GTA? If so, you can modify the following lines to get `self.model.linear_outputs` in the same session run:
https://github.com/Rayhane-mamah/Tacotron-2/blob/5582dba1aa65a94610edb9ae7ce9c58b9a705e94/tacotron/synthesizer.py#L53-L58

About the 320k, it is my way to say "number of test steps is still under test, feel free to change it" :)
However, 7 sec/step is way slower than it should be. I run models with batch_size = 32 and outputs_per_step = 1 at a speed of 1.7 sec/step using a Titan Xp. For r=2 and batch_size=48 it takes 1.2 sec/step. I am wondering if your slowdown is caused by the model itself or the feeder pipeline..

Could you report approximatively how long are your output sequences? (number of frames)
Also, could you report how long it takes the feeder to generate batches of 32?
Some monitoring of your GPU activity to know if it drops and for how long is also helpful.

**Comment by switchzts** [comment]
Thanks for your reply. About GTA,ok I found it,Thanks
Generated 32 train batches of size 32 in 1.773 sec
I dont find how to check my output sequences, I'm really a novice in this field :) Here are some information:
` 129 [2018-05-25 21:50:19.135]    embedding:                (?, ?, 512)
 130 [2018-05-25 21:50:19.135]    enc conv out:             (?, ?, 512)
 131 [2018-05-25 21:50:19.135]    encoder out:              (?, ?, 512)
 132 [2018-05-25 21:50:19.135]    decoder out:              (?, ?, 80)
 133 [2018-05-25 21:50:19.135]    residual out:             (?, ?, 512)
 134 [2018-05-25 21:50:19.135]    projected residual out:   (?, ?, 80)
 135 [2018-05-25 21:50:19.135]    mel out:                  (?, ?, 80)
 136 [2018-05-25 21:50:19.135]    linear out:               (?, ?, 513)
` There are so many ? in there ,Is it normal?  
I have tried running without predicting linear outputs , it also doesn't work so I don't think linear was a problem. I also think 2 sec/step is a normal speed. 
I used thchs30 dataset just like LJSpeech.

**Comment by switchzts** [comment]
Besides
`self._cell = tf.nn.rnn_cell.LSTMCell(num_units, state_is_tuple=state_is_tuple, name=name)`
I got an error`self._cell = tf.nn.rnn_cell.LSTMCell(num_units, state_is_tuple=state_is_tuple,name=name)
TypeError: __init__() got an unexpected keyword argument 'name'`
I think it was a problem about vision of tf, so I got rid of name=name, does that matter? My tf version was 1.4.0

**Comment by Rayhane-mamah** [comment]
Hello @switchzts sorry for the late reply.

First of all, about the alignments, if the model tends to converge very slowly, you should set `mask_decoder` to False:
https://github.com/Rayhane-mamah/Tacotron-2/blob/fb5564b7584ae0dc62ffecaa89d463ff24a3c251/hparams.py#L87

Next, you guessed right, the name was a problem with tf 1.4 version, and I believe simply taking it off doesn't cause problems.

My saved models are also about 250M. We reuse model parameters between the train model and eval model. i.e: we create two models, one that is trained on training data, the other is tested against test (unseen) data, and both share the same parameters. I like to use such techniques when making evaluations every few steps of training for overfit detection or other.

To come back to the speed problem, could you confirm that both following options are set to False? (if not please set them to False and retry):
https://github.com/Rayhane-mamah/Tacotron-2/blob/fb5564b7584ae0dc62ffecaa89d463ff24a3c251/hparams.py#L128
https://github.com/Rayhane-mamah/Tacotron-2/blob/fb5564b7584ae0dc62ffecaa89d463ff24a3c251/tacotron/models/modules.py#L151

Could you also report your GPU-util under `nvidia-smi` during training? Thanks

**Comment by switchzts** [comment]
Hello. First,thanks for the reply~You are so nice.
Here is my option:
  `sequence_length=input_lengths,
				dtype=tf.float32,
				swap_memory=True)
#Tacotron Training
	tacotron_random_seed = 5339, #Determines initial graph and operations (i.e: model) random state for reproducibility
	tacotron_swap_with_cpu = False,`
![download](https://user-images.githubusercontent.com/20810512/40700249-5fbc21c8-640b-11e8-97b1-51cf1c2cc279.png)
r=1 and batch=32,
I dont care about speed now,if model is correct ,let it go.
What I want to ask you for help is that, I notice that your wavenet is fast-wavenet right? how can I train wavenet itself without tacotron?If I use Ground Truth mel-sep as input,does it will work?Why are you use GTA instead of the real mel?Thanks for reply~

**Comment by Rayhane-mamah** [comment]
@switchzts good question. Originally I made the pipeline so that you have to train Tacotron before the Wavenet, even when trained on Ground Truth, then I realized they can be done separately in parallel if one has 2 machines..

So, since I haven't really made a separate way to train Wavenet, there are however two "tricks" you can attempt:
- If you like coding: make a small python (or any language for that matter) script that artificially creates `tacotron_output/gta/map.txt` with the following architecture:
`path_to_audio|real_mel_path|GTA_mel_path|Sentence`

If it is just to train the Wavenet without any further log or debug use, `GTA_mel_path` and `Sentence` can be set as empty strings. Note that in our repo despite requesting running the GTA before training Wavenet, it is merely to have all paths to real and GTA mels in the same log file so that training with one or the other can be done easily without having to go back to the Spectrogram Prediction Network.

- Cheat the system: If you don't have time to create a script, but can afford to wait about an hour for GTA synthesis, you can easily set [Tacotron train steps](https://github.com/Rayhane-mamah/Tacotron-2/blob/e2f9780b18648b8d0b671e1c85dd95d20d6f8553/train.py#L104) to 1 and train the entire model using the arguments **--model='Tacotron-2'** (this is default behavior even without arguments). The model will be trained one step, checkpoint, make GTA synthesis and train Wavenet. Any cancel and resume from that point will assume Tacotron is trained and the model only needs to keep training Wavenet.

**Comment by Rayhane-mamah** [comment]
hello again, a separate wavenet preprocessing script has been added if you want to use wavenet as standalone model. Feel free to reopen if you encouter issues with that ;)
