### ISSUE TITLE
adding padding to inputs, targets at wavemet_vocoder.feeder.py seems wrong

### ISSUE THREAD

**Issue by a3626a** [Rayhane-mamah/Tacotron-2#55]
wavenet_vocoder.feeder.py add padding to inputs and targets by this code :

https://github.com/Rayhane-mamah/Tacotron-2/blob/fb5564b7584ae0dc62ffecaa89d463ff24a3c251/wavenet_vocoder/feeder.py#L364-L368

I think valid padding value should be 'silence', which is `0.0` for raw input mode, `0.0=mulaw(0, 256)` for mulaw, `128=mulaw_quantize(0, 256)` for mulaw quantization.

When `input_type="mulaw-quantize"`, `zeros([256])` is padded to `inputs`, not `one_hot(128, 256)` and `0` is padded to `targets`, not `128`.

**Comment by a3626a** [comment]
Ok, I will check r9y9/wavenet.

**Comment by a3626a** [comment]
r9y9's wavenet vocoder has same bug. r9y9 will fix it.

**Comment by Rayhane-mamah** [comment]
Hello @a3626a despite this being a bug, it doesn't seem to have much effect on training, just like feeding a silent frame as initial frame during evaluation isn't always correct. Still leaving that as is for now but I will fix this some other time. closing the issue for the time being to set place for higher priority issues.

Thank you very much for this contribution!
