### ISSUE TITLE
hparams.py missing use_speaker_embedding parameter

### ISSUE THREAD

**Issue by a3626a** [Rayhane-mamah/Tacotron-2#56]
If I set gin_channels as positive, then I got error because of missing `use_speaker_embedding `.

**Comment by Rayhane-mamah** [comment]
Hello @a3626a thanks for reaching out!

Yes I am aware of that, As I mentioned before, Global conditioning is not yet ready to use. Thank you for your patience

**Comment by Rayhane-mamah** [comment]
Hello @a3626a global conditioning has been added. Feel free to reopen the issue if you find other issues related to it
