### ISSUE TITLE
Are there metrics on training speed per iteration in Tacotron

### ISSUE THREAD

**Issue by alexbeloi** [Rayhane-mamah/Tacotron-2#59]
Hi,

Thank you for the great effort put into this project. 

In an older issue (https://github.com/Rayhane-mamah/Tacotron-2/issues/11) I saw it mentioned that  @butterl was getting about 7s/iteration in training, this is 10x faster than what I am experiencing. I am curious if you or @butterl have some recent metrics on training speed with typical hyper parameters (defaults from some recent commit), or if you could confirm that what I am experiencing is in the normal range for the current project state.

Tacotron (batch_size=16, all else default):
* CPU only (core i7 960): 70-75s per iteration
* GPU (K80): 8-9s per iteration

I understand this is highly dependent on hyperparameters, I just want to make sure there isn't something horribly wrong with my hardware or something else.

**Comment by butterl** [comment]
@alexbeloi    the 7s train speed/step is based on a server with 24 core and 32GB memory (batch_size 32 and output_per_step=5) and the repo HEAD is much slower trained with cpu

For memory usage with GPU， batch_size = 48 and output_per_step=2 will use all of 16GB gpu memory with train speed 2.1s/step and GPU core usage about 45%

**Comment by alexbeloi** [comment]
@butterl Thanks for the info!

One last question, the 2.1s/step on GPU is on a single P100 or distributed over two?

**Comment by butterl** [comment]
single P100 , speed， and seems the GPU is not running full from my side, not sure if the feeder reason or just my harddisk is the bottleneck .  Maybe @Rayhane-mamah know more about optimization of the train speed

**Comment by alexbeloi** [comment]
@butterl thanks for the extra info. Cheers

**Comment by blacksph3re** [comment]
I tried training on a Geforce 1080 TI which yielded 4sec/it and on a V100 with 3sec/it. I don't know what the bottleneck is, I played around with batch size and outputs_per_step but could not get any significant improvement over that
