### ISSUE TITLE
Training on Google Compute Engine 

### ISSUE THREAD

**Issue by SRHyd** [Rayhane-mamah/Tacotron-2#68]
Hello Rayhane,

I have listened to the sample produced by this project. They are Amazing!!!, Great Work!!!

Now, I want to train English(Indian accent) on Tacotron-2. I have setup Compute Engine with configuration '4' CPUs and '8' Tesla K80 GPUs. 

I have enabled the use_all_gpus=True and num_gpus=8 in hparams.py. The training seems very slow 5sec/step.  I verified the GPU usage by uisng the tool "nvidia-smi".  It shows only one GPU is being used (output below).

| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    89W / 149W |   8398MiB / 11441MiB |     62%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:00:05.0 Off |                    0 |
| N/A   39C    P0    68W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:00:06.0 Off |                    0 |
| N/A   35C    P0    56W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:00:07.0 Off |                    0 |
| N/A   40C    P0    72W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 00000000:00:08.0 Off |                    0 |
| N/A   32C    P0    57W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 00000000:00:09.0 Off |                    0 |
| N/A   40C    P0    68W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 00000000:00:0A.0 Off |                    0 |
| N/A   35C    P0    57W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 00000000:00:0B.0 Off |                    0 |
| N/A   38C    P0    71W / 149W |    112MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
I am wondering if multiple GPUs are supported in this project?

Thank you,
SRHyd

**Comment by SRHyd** [comment]
Just found #43. Multi-gpu support is not present.

**Comment by Cecilwang** [comment]
gcloud is a nice choice. If you want to run with multi-gpu, you can wrap model with tf.estimator.EstimatorSpec then call tf.contrib.estimator.replicate_model_fn to create model_fn for tf.estimator.Estimator, now you can use all the gpus.

**Comment by SRHyd** [comment]
Thank you @Cecilwang. I will try this.
