### ISSUE TITLE
Both encoder and decoder masking could be considered harmful

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#71]
I strongly suggest disabling both `mask_encoder` and `mask_decoder` for we might well fail to convergence due to encoder masking and get stuck during early training due to decoder masking if we want linear spectrograms output without wavenet.
![image](https://user-images.githubusercontent.com/6031938/41454101-c33cfce4-70aa-11e8-841c-71ae75747d4b.png)

**Comment by SRHyd** [comment]
@begeekmyfriend, I am training 16KHz dataset by disabling mask_encoder and mask_decoder.  
mask_encoder = False, 
mask_decoder = False,

I also changed the decoder params...
prenet_layers = [128, 128], # original value - [258, 258]
decoder_layers = 2,  #number of decoder lstm layers
decoder_lstm_units = 512, # original value - 1024

But no alignment after 5K, the align plot looks as below. 
![step-5000-align](https://user-images.githubusercontent.com/40122465/41454860-a6bd2a92-7098-11e8-87b3-4b4e70399008.png)

**Comment by begeekmyfriend** [comment]
Maybe you need to revert your decoding parameters?

**Comment by Rayhane-mamah** [comment]
@begeekmyfriend it's True that it's often harder to train with masks, as a following of this issue, I set the masks to False as default. Thanks for your contribution :)
