### ISSUE TITLE
Have question about the WaveNet Causal Conv

### ISSUE THREAD

**Issue by liusongxiang** [Rayhane-mamah/Tacotron-2#76]
Hi, thanks for the great repo. I have a question here.
The line 110 in Tacotron-2/wavenet_vocoder/models/modules.py shows:
`cropped = tf.slice(outputs, [0, 0, crop], [-1, -1, -1])`
I think it should be
`cropped = tf.slice(outputs, [0, 0, 0], [-1, -1, new_shape[0]-crop])`
Am I right?

**Comment by a3626a** [comment]
https://github.com/Rayhane-mamah/Tacotron-2/blob/e2f9780b18648b8d0b671e1c85dd95d20d6f8553/wavenet_vocoder/models/modules.py#L62-L87

Padding is added to the left. Therefore, cropping out left seems like valid.

**Comment by Rayhane-mamah** [comment]
Hello @liusongxiang, @a3626a answer is perfectly correct. i hope this answers your question.
You can refer to [fast wavenet official implementation](https://github.com/tomlepaine/fast-wavenet) for more insight about this. Feel free to reopen the issue if needed. :)
