### ISSUE TITLE
Difference between training methods

### ISSUE THREAD

**Issue by ishansan38** [Rayhane-mamah/Tacotron-2#78]
Hi. A simple question, wasn't clear from the docs.
What is the difference b/w 
`python train.py --model='Tacotron-2'`
and 
`python train.py --model='Both'`

Are both sequential?

**Comment by gsoul** [comment]
There are 2 parts to this repo: encoder (Tacotron-2) and decoder (WaveNet)

"Both" - trains 2 models, "Tacotron-2" - only 1 model

**Comment by ishansan38** [comment]
@gsoul Okay, but train.py says something like this:
https://github.com/Rayhane-mamah/Tacotron-2/blob/master/train.py#L120

**Comment by v-yunbin** [comment]
@gsoul do you mean "Both" - trains tacotron and tacotron2 model?

**Comment by tomse-h** [comment]
`Tacotron-2` and `Both` train the whole System (Encoder and Decoder), whereas `Tacotron` and `Wavenet` train the individual components. It just appears that you have two ways to call training on the whole thing.
