### ISSUE TITLE
nv-wavenet related question(s)

### ISSUE THREAD

**Issue by gaziway** [Rayhane-mamah/Tacotron-2#79]
First of all thank you for releasing the codes. 
We are working on the TTS for some minor languages. So far the easiest to train and the best performing models we generated are based on this repo. Yet another exciting repo is the one for near real time wavenet implementation: https://github.com/NVIDIA/nv-wavenet/.
We would like to know do you plan some kind of integration of your Tacotron implemantion and the nv-wavenet. We tried to directly feed wavs produced by this repo to the https://github.com/NVIDIA/nv-wavenet/blob/master/pytorch/inference.py and results are promising. But still porting your implementaiotn to nv-wavenet will be very beneficial!

**Comment by switchzts** [comment]
hey "We tried to directly feed wavs produced by this repo to the https://github.com/NVIDIA/nv-wavenet/blob/master/pytorch/inference.py " do you have any progress?

**Comment by rishikksh20** [comment]
@gaziway Please share the details how you feed mel-spectrogram generated by this repo to nv-wavenet, what setting you change or so .

**Comment by Rayhane-mamah** [comment]
Hello there, I should point out that the nv-Wavenet is very different from our Wavenet architecture, still if you plan on using it, you can copy our upsampling network and make use of it as upsampling prior to nv-Wavenet.
https://github.com/Rayhane-mamah/Tacotron-2/blob/c205b45588bd2e4765bf318ccd11e5ed8a64aac9/wavenet_vocoder/models/wavenet.py#L128-L140

I don't have any plans on making intergration with nv-Wavenet as it would require much change on nv-Wavenet c++ code to make it similar to the Wavenet architecture I use (to keep audio quality).

An alternative would be to make use of [parallel wavenet](https://arxiv.org/abs/1711.10433) but I leave that in the hands of mighty coders :)

I hope this answers the question. If I can help with anything else, feel free to reopen :)
