### ISSUE TITLE
Incompatible shapes: [48, 875, 80] vs [48, 880, 80]

### ISSUE THREAD

**Issue by imdatsolak** [Rayhane-mamah/Tacotron-2#8]
Hi @Rayhane-mamah, after checking out the newest commit, I get the following error quite quickly after training starts:

`Exiting due to exception: Incompatible shapes: [48,875,80] vs. [48,880,80]`

Any idea what it could be?

**Comment by a3626a** [comment]
It could be thrown when target mel sequence and generated mel sequence have different length.

**Comment by imdatsolak** [comment]
I found out that it is related to token_length/target_length. Needs to be checked in `hparams.py`. The number `875` (e.g.) is calculated using:

`hparams.max_iters * hparams.outputs_per_step`

In my case, some of my targets were larger than the default setting. Changing `hparams.max_iters` to `256` solved the case.

Thanks

**Comment by Rayhane-mamah** [comment]
Hello @imdatsolak, After seeing this issue I have set the max iterations limitation to only work at synthesis time. So you can rest assured for future commits, max_iters will only affect the length of your generated mels at synthesis time.

Thank you very much for reporting the issue.
