### ISSUE TITLE
22050Hz should be the baseline sample rate for synthesis quality

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#80]
Here are the difference in spectrograms between sample rates as 16kHz and 22050Hz. Sadly I am afraid I have made a huge mistake. Now I have to re-sample all my 16KHz dataset to get better quality...
![image](https://user-images.githubusercontent.com/6031938/41693607-af245da0-7538-11e8-8453-11b6d073eb17.png)
![image](https://user-images.githubusercontent.com/6031938/41693644-db2c4674-7538-11e8-8472-e6927bde3801.png)

**Comment by butterl** [comment]
@begeekmyfriend  these two are trained with same datasets and with different sample rate？

**Comment by switchzts** [comment]
效果听起来差距非常大吗？16k的合成听起来也还行就是没细节

**Comment by begeekmyfriend** [comment]
Insignificant. Close it.
