### ISSUE TITLE
PortAudio library not found

### ISSUE THREAD

**Issue by v-yunbin** [Rayhane-mamah/Tacotron-2#81]
when kick off train, met the follow error:
data02/zhangyb/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from tacotron.synthesize import tacotron_synthesize
  File "/data02/zhangyb/Tacotron-2/tacotron/synthesize.py", line 5, in <module>
    from tacotron.synthesizer import Synthesizer
  File "/data02/zhangyb/Tacotron-2/tacotron/synthesizer.py", line 10, in <module>
    import sounddevice as sd
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/sounddevice.py", line 70, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

**Comment by cobr123** [comment]
try pip install -r requirements.txt

**Comment by v-yunbin** [comment]
3ks, i solved it by installing portaudio: https://www.cnblogs.com/dbj66/p/8817890.html

**Comment by mikechen66** [comment]
The quick way is to install libportaudio2 as follows. 

$ sudo apt-get install libportaudio2

source: https://stackoverflow.com/questions/49333582/portaudio-library-not-found-by-sounddevice
