### ISSUE TITLE
can not synthesize audio like human voice when execute "python synthesize.py --model='WaveNet'"

### ISSUE THREAD

**Issue by cuicp** [Rayhane-mamah/Tacotron-2#82]
Hi,  I trained the Tacotron-2 model with the latest code(e2f9780b186). The command was "python train.py --model='Both' ". During the training process, I found that the model synthesized some good quality audio "logs- Both/wavs/step-*-pred.wav”, but when I execute the command “python synthesize.py”, I get the following error:
NotFoundError (see above for traceback): Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAver found not found in checkpoint

Although the author said that this problem has been solved  [issue52](https://github.com/Rayhane-mamah/Tacotron-2/issues/52)  , I still have this problem.

Then i performed the following operations in the workspace:
(1) mkdir logs-Wavenet
(2) cp -r logs-Both/wave_pretrained/ logs-WaveNet/
(3) python synthesize.py --model='WaveNet'
and the WaveNet model loaded successful, but the synthesized audio is not like human voice.
Has anyone encountered this problem? If someone solves this problem I would be very grateful !

there are two examples, which 'step-70000-pred.wav' is the audio synthesized in training process,
and 'speech-audio-00001.wav' is the audio synthesized after i execute "python synthesize.py --model='WaveNet' "
[wav.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2125899/wav.zip)

**Comment by wkunique** [comment]
This may be helpful 
:NotFoundError (see above for traceback): Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAver found not found in checkpoint

```
--- a/synthesize.py
+++ b/synthesize.py
@@ -31,6 +31,8 @@ def synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences):
        log('Synthesizing mel-spectrograms from text..')
        wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
        log('Synthesizing audio from mel-spectrograms.. (This may take a while)')
+       import tensorflow as tf
+       tf.reset_default_graph()
        wavenet_synthesize(args, hparams, wave_checkpoint)
        log('Tacotron-2 TTS synthesis complete!')
```

**Comment by v-yunbin** [comment]
@cuicp I met same error, do you have solve it?

**Comment by NewEricWang** [comment]
@cuicp I also met same error, do you have solve it? 
I used command "python synthesize.py --model='WaveNet'", but I only got full-noisy audio. The used model is 360k-step wavenet model on LJ-speech database.  I found the pred-wave in eval-dirs/wavs also is noise.  I guess the wavenet don't coverage at 360k-step.
