### ISSUE TITLE
questions on the final .wav file

### ISSUE THREAD

**Issue by zhangyizhong17** [Rayhane-mamah/Tacotron-2#83]
Firstly, thanks for publishing this amazing code.
I m on the final step. All the training has been done. The plots of the wave seem super cool, however the .wav files sound like white noises. I went through the code, the save_wave and save_plot are both using the generated_wav. Since the waveplots are correct, the generated_wav should be ok. And the wavfile.write function is imported from the scipy.io module. So why did I get a white noise .wav file? Did I miss something?

**Comment by zhangyizhong17** [comment]
I m trying to figure out how to upload the image... images cannot be attached somehow... it seems something wrong with my browser?

**Comment by zhangyizhong17** [comment]
![qq 20180622153317](https://user-images.githubusercontent.com/40283943/41764041-8470e0a6-7632-11e8-9706-d61cc5bb9c9d.png)
![qq 20180622152446](https://user-images.githubusercontent.com/40283943/41764052-8a7fadb0-7632-11e8-843f-806719aa3799.png)
![qq 20180622152453](https://user-images.githubusercontent.com/40283943/41764055-8d4aa3ba-7632-11e8-976b-7187b843a4cb.png)

**Comment by zhangyizhong17** [comment]
![qq 20180622155158](https://user-images.githubusercontent.com/40283943/41764597-37c3442c-7634-11e8-8437-7c67ce28e754.jpg)
and this is how the .wav file looks like, which doesn't match the wave plot generated by the code.

**Comment by orionpeng** [comment]
@zhangyizhong17  Any updates? 
I meet the same problem that the wave plot generated by the code doesn't match the true waveform.

**Comment by zhangyizhong17** [comment]
@orionpeng 
I ploted the generated_wav by matlab instead of using the code. It did have problems. 
Besides, it seems the loss of wavenet failed in convergence.
I didn't find out a way of making it better. So I m trying on other wavenet codes now.

**Comment by orionpeng** [comment]
@zhangyizhong17 
Thx for your comment! Very helpful!

**Comment by harlyh** [comment]
@zhangyizhong17, to me it seems your wav overflows np.int16
did you debug your np.max(np.abs(wav)) value? 
What if you temporarily uncomment the 
wav *= ... line?

**Comment by zhangyizhong17** [comment]
@harlyh 
the "wave *= ..." line is ok.
The generated_wav is the problem (which is the input of the 'np.max(np.abs(wav))' value).
the generated_wav looks exactly like the .wave file shows, but the waveplot function in code somehow get a reasonable wave. the plot is actually doing a symmetric transformation of the generated_wav itself.
the upper one is the generated_wav, the bottom one is the ploted_wav.
![qq 20180628170816](https://user-images.githubusercontent.com/40283943/42025068-4e1b07f2-7af6-11e8-9987-09ad2acb7b1a.png)
![qq 20180628170821](https://user-images.githubusercontent.com/40283943/42025075-5104f5fe-7af6-11e8-8466-b7d580e2582e.png)
