### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by Jeff-Winchell** [Rayhane-mamah/Tacotron-2#84]
"After downloading the dataset, extract the compressed file, and place the folder inside the cloned repository"

Change that to "in the main directory of the cloned repository" to make this clearer.

python preprocess.py --dataset='M-AILABS' --language='en_US' --voice='male' --reader='elliot_miller' --merge_books=True

quotes don't work or at least they don't under WIndows. So this needs a change or a documentation note.

--base_dir= whatever   
make clear to the reader that this affects both the input and output (i.e. the risks of wiping out your previous output from a previous run

Because new people will want to experiment with different hyperparameters and data, document should give you ideas on how to keep all those versions intact without them getting wiped out the way the current programs will do.

It would be good to download smaller parts of M-AILABS because it takes many hours to download the whole thing. Not sure you can do anything about that unless there is a program to download only part of an archive file.

Also, the graphs and wav files created during training should be hilighted in the getting started documentation. I assume the diagonal line graph should ideally have a slope of 1.0. Point that out to the new user so they can figure out if something is going wrong.
Also explicitly say to look at the predicted and actual mel graphs - maybe show them a couple examples of how good matches look, how bad pairs look and one pairing that is meh.

Give some ideas about how long things should take on machine with XYZ Cuda Cores, no GPU, and how much GPU or main memory.

**Comment by Jeff-Winchell** [comment]
Possibly this and every other text comparison line in preprocess is failing is because I run on Windows and somehow the characters in the python scripts can't deal with characters fed into it at a Windows command line??

**Comment by Rayhane-mamah** [comment]
You can make use of "--name" argument to not wipe out previous trainings. other points have been discussed I think.

I will try working on better documentation, thanks for the feedback :)
