### ISSUE TITLE
data_format must be "NHWC" or "NCHW"?

### ISSUE THREAD

**Issue by v-yunbin** [Rayhane-mamah/Tacotron-2#87]
commad: nohup /data02/anaconda3/python3 train.py --model='Tacotron-2'
error:   feeder.input_lengths, x=feeder.inputs)
  File "/data02/Tacotron-2/wavenet_vocoder/models/wavenet.py", line 169, in initialize
    y_hat = self.step(x, c, g, softmax=False) #softmax is automatically computed inside softmax_cross_entropy if needed
  File "/data02/Tacotron-2/wavenet_vocoder/models/wavenet.py", line 443, in step
    x = self.first_conv(x)
  File "/data02/Tacotron-2/wavenet_vocoder/models/modules.py", line 126, in __call__
    stride=1, padding='VALID', data_format='NWC')
  File "/data02/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2199, in conv1d
    raise ValueError("data_format must be \"NHWC\" or \"NCHW\".")
ValueError: data_format must be "NHWC" or "NCHW".

**Comment by v-yunbin** [comment]
solved it.

**Comment by DanRuta** [comment]
Hi @v-yunbin . What steps did you take to solve this?

**Comment by v-yunbin** [comment]
just install 1.8 version tensorflow, because new version tensorflow have fixed the error.

**Comment by v-yunbin** [comment]
after install tensorflow and rerun train, get still some below error, 
Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: model_1/inference/conv2d_transpose/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 16], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model_1/inference/conv2d_transpose/stack, model/inference/conv2d_transpose/kernel/read, model_1/inference/ExpandDims_1)]]
_next step is to change NCHW to NHWC._

**Comment by v-yunbin** [comment]
I have training the wavenet normally, below information can be a reference:

OS Platform: CentOS Linux release 7.3.1611 (Core)
TensorFlow installed from: binary (use "pip" to install it )
TensorFlow version:  tensorflow-gpu 1.8 (use "pip" to install it )
Python version: anaconda 3.5
CUDA/cuDNN version: cuda-9.0
GPU model and memory: 1T
