### ISSUE TITLE
Aborted message when training using GPU

### ISSUE THREAD

**Issue by zliuar** [Rayhane-mamah/Tacotron-2#89]
Hi, I am a beginner at tensorflow. 
I got this output and the program stopped when I am running train.py with default settings using tensorflow-gpu-1.8.0.

> Generated 32 train batches of size 48 in 4.908 sec
Generated 48 test batches of size 48 in 9.417 sec
Aborted

But when I uninstall the gpu version of tensorflow and use the cpu version, the program could run successfully.

Anyone could help me with that?

Thank you very much!

**Comment by v-yunbin** [comment]
it seems the script only support cpu!!!

**Comment by zliuar** [comment]
@v-yunbin Thank you for your reply! But I still don't understand why a neural network like tacotron can not be trained with GPU. Any reason behind it? By the way how do we identify whether a script support GPU or not?

Thanks again for your help!

**Comment by Jeff-Winchell** [comment]
The script runs with GPUs with no changes to the script. In fact, I can't see how one could ever hope to train anything useful without a GPU since even a very high powered GPU can take 6 days to fully train the TacoTran part of the model.

There is something else wrong going here.

Have you verified your Tensorflow is using a GPU correctly (Google for simple code that demonstrates that if you haven't already).

**Comment by zliuar** [comment]
@Jeff-Winchell Thanks for your explanation. I believe you are right. This is not natural for a tensorflow program not running with GPUs when it is not explicitly specified to use CPU (except the feeder). I am to check the simple code online. 

By the way, do you have any idea where the message "Aborted" comes? I searched the programs in this project and no results returned. And I couldn't find any error message in python which explains my case. I have no idea which script returned this print out message 'Aborted'. Can you help me with it?

Thanks for your help!

**Comment by Jeff-Winchell** [comment]
As for the Aborted message,  who knows. A problem with most software today is that it relies on so many 3rd party libraries, which themselves rely on more libraries, which rely on even more libraries, that who knows what the cause of most problems is.

Eventually with any software that really matters, I strip out the 90+% (or 99.9%) of the code that I don't need. So that I only have code that does exactly what I want and I understand 100% of the code I ship.

**Comment by harlyh** [comment]
Which GPU are you using? How much memory it has?

**Comment by Jeff-Winchell** [comment]
Rayhayne mentioned to me that the aborted message sometimes happens because the tensorflow gpu driver is not quite right. If you are running linux, redoing the gpu driver might easily do the trick. If you are running windows you need to do a recompile... this takes following some detailed instructions which takes about 5 hours most of that time for the c code to recompile.

**Comment by zliuar** [comment]
@harlyh I am using a server with one TITAN Xp (12189MiB) and 6 Tesla M60 (7613MiB). When I am running the train.py, I am running with this code to use the GPU with number 2 (a Tesla M60 which is available at that time):

> CUDA_VISIBLE_DEVICES=2 python train.py

Then I got the aborted message returned.
I also tried the following code to force the tensorflow to use cpu even the version of tensorflow is also tensorflow-gpu-1.8.0.

> CUDA_VISIBLE_DEVICES='' python train.py
I still got the message.

However, after I uninstalled the tensorflow-gpu and install the tensorflow (which should use CPU), I could run the program with no same message returned.

Thanks for your help!

**Comment by zliuar** [comment]
@Jeff-Winchell Thank you for your help! I will definitely want to try you solution. It seems like the environment is not ready.

**Comment by harlyh** [comment]
@zliuar, I guess if you've got tons of CPU cores on multiple machines then of course you could in train and later run it on CPU too. I'm not convinced, however, that you'd be happy with the performance.

I'm just going to leave some of my benchmarking results from a test that I performed with a very limited and small custom audio corpus - in total less than an hour of audio (~400 audio samples):
* CPU (AMD Ryzen 2700x) result: used all 8 cores and 16 threads. Got an average of ~33 sec/step
* GPU (NVIDIA GTX 1080ti) result: ~1.2 sec/step, that after 10k steps gradually went down to ~0.8sec/step

Now with large corpus (such as LJspeech) this GPU was doing about 3-4sec/step, didn't test on CPU, though. But I suspect that with corpus size growth the difference would grow exponentially.

**Comment by zliuar** [comment]
@harlyh Thank you for your sharing!

I checked the CPU information on my server. It has 48 CPU cores (Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz).

The training time of the frontend (tacotron) part is 19 secs/step using around 24 CPU cores.

Of course I really expect to train with GPUs right now. However, as you can see, I have to solve the error message first. QAQ. Thanks to everyone's help, I hope I could solve this problem as early as possible. >_<

Thanks for your reply!

**Comment by zliuar** [comment]
@everyone
I solved the problem. I didn't change anything, and I just get a empty GPU with enough memory. I guess this should be a memory problem.

Thanks for everyone's help!

**Comment by ddevops** [comment]
** @zliuar** Could you please elaborate more that how did you solve your issue? I am also facing the same issue. 

I am able to run other models than Tactoron on the same machine but Tacotron exists as soon as its done with initializing GPUs

```
Generated 20 test batches of size 32 in 2.001 sec

Generated 64 train batches of size 32 in 5.194 sec
Aborted
```

**Comment by zliuar** [comment]
Hi, @ddevops , sorry to hear that you had the same problem. I believe it should be a problem similar to OOM. Since when i am not sharing the GPU with other users, it works quite fine. What i mean is that the cause of this problem is lack of adequate GPU memory. You may try the following ways to reduce the memory needed. Actually, you may refer to all the OOM issues associated with this project.

1. You may increase the output_per_step parameter. Desired values should be 1 or 2 or 3 according to other previous issues.
2. You may decrease the training batch size. It is suggested be larger than 32 though.
3. You may train with a GPU with larger memory. Usually 11GB - 12GB memory works well for this project. I could also use 8GB with a batch size around 40 though.
4. Make sure the GPU's memory is totally free when you train your model.

If the above couldn't solve your problem, please list the hardware info to help. Frankly speaking, i am not 100% sure whether the cause is exactly as what i thought. ><

**Comment by ddevops** [comment]
@zliuar Thank you for your reply but I don't think its an OOM related issue because I have 4 GPU's of 32GB memory. These are even in ideal state. 

`0MiB / 32502MiB`

**Comment by zliuar** [comment]
Okay... Could you list the version of your python, tensorflow-gpu, cuda and cudnn?

**Comment by ddevops** [comment]
```
python -V                                                                                                                                |
Python 3.6.8 :: Anaconda, Inc.

CUDA Version 9.0.176

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

CUDNN version 7.1.4

tensorboard                        1.8.0         
tensorboardX                       1.1           
tensorflow-gpu                     1.8.0
```

**Comment by ddevops** [comment]
Okay the issue is resolved for me now. It was something related to CUDA and CUDNN drivers incompatibility MAYBE. I reconfigured all the requirements with Conda, setup a new environment and it started working this time.

**Comment by 416207298** [comment]
> Okay the issue is resolved for me now. It was something related to CUDA and CUDNN drivers incompatibility MAYBE. I reconfigured all the requirements with Conda, setup a new environment and it started working this time.

Hey, I just met this mistake too. My running environment is as below:
```
CUDA Version 9.0.176

Python 3.6.4

cudnn verison 7.6.1

tensorflow version: 1.7.0
```
And I have one single GPU: Nvidia 1080Ti with 8G memory, Maybe it's lack of memory? I modified `hparams.py` told by @zliuar in order to use less of GPU memory. But it didn't change anything.
I try to reinstall cuda and cudnn as well, but it still don't work as it aborted as always...

Could you told me how you figure it out more detailedly? Thanks for any help!

**Comment by ddevops** [comment]
Please try to setup with Anaconda Python. It worked for me.

**Comment by 416207298** [comment]
> Please try to setup with Anaconda Python. It worked for me.
> […](#)

Okey, I'll try it.
