### ISSUE TITLE
Code not making use of GPU

### ISSUE THREAD

**Issue by ishansan38** [Rayhane-mamah/Tacotron-2#97]
![screenshot from 2018-07-06 22-22-18](https://user-images.githubusercontent.com/21282864/42390967-5b6f2a84-816b-11e8-8789-98e9485955ad.png)

I am running train.py --model='Both' but the training time per step is 58 seconds, too slow.
On running nvidia-smi, it shows the GPU is not being utilized. Is there something I am missing?

**Comment by ishansan38** [comment]
I think that would work. But after installation and running train.py, the follow error occurs:

`AttributeError: module 'tensorflow' has no attribute 'contrib'
`

**Comment by hiroto911** [comment]
I think the version of tensorflow needs to be 1.6 or higher.
I am using 1.7

**Comment by ishansan38** [comment]
Hi @hiroto911 Thanks for the answer.
I have reinstalled tensorflow with gpu support.

`
tensorflow-gpu         1.7.0    
tensorflow-tensorboard 0.1.8  
`
On running train.py again, the nvidia-smi command shows no usage of GPU.
Not sure why is that happening.

**Comment by ishansan38** [comment]
Got it thanks! :)

**Comment by Rayhane-mamah** [comment]
I am assuming this has been fixed. closing the issue. If there are any further question or if the issue persists feel free to reopen :)

**Comment by kwibjo** [comment]
Same problem here. GTX 1080, CUDA 9.0 and wavenet + wavenet-gpu installed. My CPU (R7 2700x) is being pegged 90% while my gpu sits idle. If I uninstall just wavenet then I get 
`AttributeError: module 'tensorflow' has no attribute 'contrib'` error.
Snippet from output log:
```
No model to load at logs-Tacotron-2\taco_pretrained

Generated 64 train batches of size 8 in 1.379 sec

Generated 81 test batches of size 8 in 1.632 sec
Step       1 [59.480 sec/step, loss=11.39907, avg_loss=11.39907]
Saving Model Character Embeddings visualization..
Tacotron Character embeddings have been updated on tensorboard!
Step       2 [48.279 sec/step, loss=7.72918, avg_loss=9.56413]
```

**Comment by sahith1212** [comment]
I have the same issue as Ishansan38 had but, using tensorflow 1.7 is also giving the same error as
AttributeError: module 'tensorflow' has no attribute 'contrib' 
PS. i have installed latest tensorflow gpu aswell

**Comment by sahith1212** [comment]
I faced the same issue as Ishansan38 after installing tensorflow gpu and tensorflow1.7 its still giving same error:
`AttributeError: module 'tensorflow' has no attribute 'contrib'`

**Comment by coloneldbugger** [comment]
Did anyone figure out what happened here? I'm on 1.13 and having similar issues.
