### ISSUE TITLE
some tensor not stored in checkpoint files

### ISSUE THREAD

**Issue by zliuar** [Rayhane-mamah/Tacotron-2#98]
Hello, after I finished training the Tacotron 2 model including the front end and also Wavenet and I am trying to synthesize the waveform. But I got the following error.

> tensorflow.python.framework.errors_impl.NotFoundError: Key model/model/inference/decoder/Location_Sensitive_Attention/attention_bias/ExponentialMovingAverage not found in checkpoint

When I use  `inspect_checkpoint` to check the checkpoint file, I found the inference layer only has four tensors with name:

> tensor_name:  model/model/inference/conv2d_transpose/bias/ExponentialMovingAverage
tensor_name:  model/model/inference/conv2d_transpose/kernel/ExponentialMovingAverage
tensor_name:  model/model/inference/conv2d_transpose_1/bias/ExponentialMovingAverage
tensor_name:  model/model/inference/conv2d_transpose_1/kernel/ExponentialMovingAverage

Could anyone help me find out why this is happening?

Here are the tensor names of `inference` layer that I found in the model but not in checkpoint files:

> Variable:  model/inference/inputs_embedding:0
Variable:  model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/conv1d/kernel:0
Variable:  model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/conv1d/bias:0
Variable:  model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/batch_normalization/gamma:0
Variable:  model/inference/encoder_convolutions/conv_layer_1_encoder_convolutions/batch_normalization/beta:0
Variable:  model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/conv1d/kernel:0
Variable:  model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/conv1d/bias:0
Variable:  model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/batch_normalization/gamma:0
Variable:  model/inference/encoder_convolutions/conv_layer_2_encoder_convolutions/batch_normalization/beta:0
Variable:  model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/conv1d/kernel:0
Variable:  model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/conv1d/bias:0
Variable:  model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/batch_normalization/gamma:0
Variable:  model/inference/encoder_convolutions/conv_layer_3_encoder_convolutions/batch_normalization/beta:0
Variable:  model/inference/encoder_LSTM/bidirectional_rnn/fw/encoder_fw_LSTM/kernel:0
Variable:  model/inference/encoder_LSTM/bidirectional_rnn/fw/encoder_fw_LSTM/bias:0
Variable:  model/inference/encoder_LSTM/bidirectional_rnn/bw/encoder_bw_LSTM/kernel:0
Variable:  model/inference/encoder_LSTM/bidirectional_rnn/bw/encoder_bw_LSTM/bias:0
Variable:  model/inference/memory_layer/kernel:0
Variable:  model/inference/decoder/decoder_prenet/dense_1/kernel:0
Variable:  model/inference/decoder/decoder_prenet/dense_1/bias:0
Variable:  model/inference/decoder/decoder_prenet/dense_2/kernel:0
Variable:  model/inference/decoder/decoder_prenet/dense_2/bias:0
Variable:  model/inference/decoder/decoder_lstm/multi_rnn_cell/cell_0/decoder_LSTM_1/kernel:0
Variable:  model/inference/decoder/decoder_lstm/multi_rnn_cell/cell_0/decoder_LSTM_1/bias:0
Variable:  model/inference/decoder/decoder_lstm/multi_rnn_cell/cell_1/decoder_LSTM_2/kernel:0
Variable:  model/inference/decoder/decoder_lstm/multi_rnn_cell/cell_1/decoder_LSTM_2/bias:0
Variable:  model/inference/decoder/Location_Sensitive_Attention/query_layer/kernel:0
Variable:  model/inference/decoder/Location_Sensitive_Attention/location_features_convolution/kernel:0
Variable:  model/inference/decoder/Location_Sensitive_Attention/location_features_convolution/bias:0
Variable:  model/inference/decoder/Location_Sensitive_Attention/location_features_layer/kernel:0
Variable:  model/inference/decoder/Location_Sensitive_Attention/attention_variable:0
Variable:  model/inference/decoder/Location_Sensitive_Attention/attention_bias:0
Variable:  model/inference/decoder/linear_transform/projection_linear_transform/kernel:0
Variable:  model/inference/decoder/linear_transform/projection_linear_transform/bias:0
Variable:  model/inference/decoder/stop_token_projection/projection_stop_token_projection/kernel:0
Variable:  model/inference/decoder/stop_token_projection/projection_stop_token_projection/bias:0
Variable:  model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/conv1d/kernel:0
Variable:  model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/conv1d/bias:0
Variable:  model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/batch_normalization/gamma:0
Variable:  model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/batch_normalization/beta:0
Variable:  model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/conv1d/kernel:0
Variable:  model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/conv1d/bias:0
Variable:  model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/batch_normalization/gamma:0
Variable:  model/inference/postnet_convolutions/conv_layer_2_postnet_convolutions/batch_normalization/beta:0
Variable:  model/inference/postnet_convolutions/conv_layer_3_postnet_convolutions/conv1d/kernel:0
Variable:  model/inference/postnet_convolutions/conv_layer_3_postnet_convolutions/conv1d/bias:0
Variable:  model/inference/postnet_convolutions/conv_layer_3_postnet_convolutions/batch_normalization/gamma:0
Variable:  model/inference/postnet_convolutions/conv_layer_3_postnet_convolutions/batch_normalization/beta:0
Variable:  model/inference/postnet_convolutions/conv_layer_4_postnet_convolutions/conv1d/kernel:0
Variable:  model/inference/postnet_convolutions/conv_layer_4_postnet_convolutions/conv1d/bias:0
Variable:  model/inference/postnet_convolutions/conv_layer_4_postnet_convolutions/batch_normalization/gamma:0
Variable:  model/inference/postnet_convolutions/conv_layer_4_postnet_convolutions/batch_normalization/beta:0
Variable:  model/inference/postnet_convolutions/conv_layer_5_postnet_convolutions/conv1d/kernel:0
Variable:  model/inference/postnet_convolutions/conv_layer_5_postnet_convolutions/conv1d/bias:0
Variable:  model/inference/postnet_convolutions/conv_layer_5_postnet_convolutions/batch_normalization/gamma:0
Variable:  model/inference/postnet_convolutions/conv_layer_5_postnet_convolutions/batch_normalization/beta:0
Variable:  model/inference/postnet_projection/projection_postnet_projection/kernel:0
Variable:  model/inference/postnet_projection/projection_postnet_projection/bias:0

What may be wrong in my training?

Thanks for anyone could help!

**Comment by victorkohler** [comment]
Hello! Did you solve this error? Running into the same issue.

Thanks!

**Comment by dsilva-tbox** [comment]
Same issue here

**Comment by zliuar** [comment]
@victorkohler @dsilva-tbox You may refer to this issue #82.

**Comment by Yeongtae** [comment]
use #https://github.com/Rayhane-mamah/Tacotron-2/pull/110
