### ISSUE TITLE
Style transfer?

### ISSUE THREAD

**Issue by sizzles** [Rayhane-mamah/Tacotron-2#99]
Hi

I'm quite new to this particular field - I'm interested in style transfer in particular. Eg as: https://github.com/lengstrom/fast-style-transfer

Would anyone have any pointers on where this could slot into the Tacotron-2 model? From the diagram in the readme I would guess after the decoder?

Thanks
Alex

**Comment by Rayhane-mamah** [comment]
Hello @sizzles this is a fine idea you got there.

I am not entirely sure on how to proceed with this, but according to previous style works on speech, I believe you should integrate this right before the decoder (as additional encoder ouputs). With this said, here are few style learning and transfer papers that might be helpful.

- https://arxiv.org/abs/1803.09047
- https://arxiv.org/abs/1803.09017

Please keep in mind that this implementation is merely a base to build on so initiatives like yours are brilliant! 
Also please keep in mind that issues are meant to report bugs made in the repo. if you want to develop this discussion, I envite you to join the Tacotron-2/slack in this link:
https://join.slack.com/t/tacotron2/shared_invite/enQtNDA4MzAzMzY4MjcyLTg3N2ZjZDkyZTAyYjdmNDc2MmFmNjA5NTQ0Mzk3NzgyNjljZGE1YWU4OWFmYjFmYzI4OGE2YWM4MGY4NmRkNGY
